### ISSUE TITLE
tendermint::PrivateKey doesn't derive Copy or Clone

### ISSUE THREAD

**Issue by zbuc** [informalsystems/tendermint-rs#1077]
The `tendermint::PrivateKey` enum doesn't derive Copy or Clone, but the underlying `ed25519_consensus::SigningKey` contained by the enum supports both.

I was able to work around this by cloning the inner value:

```rust
let cloned_key = tendermint::PrivateKey::Ed25519(
   other_key.ed25519_signing_key().unwrap().clone(),
);
```

but it'd be nicer to be able to Copy/Clone the type directly if possible.

**Comment by tony-iqlusion** [comment]
Would strongly recommend explicit `Clone` over `Copy`. You don't want to indiscriminately make copies of private keys.

**Comment by zbuc** [comment]
Good point, we'll update `ed25519-consensus` as well
