### ISSUE TITLE
rpc: Remove ABCI-related types

### ISSUE THREAD

**Issue by thanethomson** [informalsystems/tendermint-rs#1090]
Version(s) of tendermint-rs: `master`

### Description

Follows from #1022, which introduced domain types into the `tendermint` crate for ABCI. The RPC crate used to have ABCI-specific data structures to use in its responses, but these have been superseded by the ABCI domain types in the `tendermint` crate.

[These old ABCI RPC data structures](https://github.com/informalsystems/tendermint-rs/blob/904862c7c2db6a2b7a926af2ac8e3d7428f8779f/rpc/src/abci.rs) must be removed.

### Definition of "done"

When all of the [old ABCI RPC data structures](https://github.com/informalsystems/tendermint-rs/blob/904862c7c2db6a2b7a926af2ac8e3d7428f8779f/rpc/src/abci.rs) have been removed.

**Comment by mzabaluev** [comment]
Some questions while working on #1204:

* In the [response struct](https://github.com/informalsystems/tendermint-rs/pull/1204/files#diff-8b372f30a4017d2a935c3db771835904c928aa48fced8fd30e55c8890581c8d2R43) for `/broadcast_tx_commit`, do we care to change the `check_tx` and `deliver_tx` method to the corresponding domain types from the `tendermint` crate? Serde for `TxResult` reflects some quirks that may be only relevant for this endpoint, and also features the `mempool_error` field which is consciously omitted from the `abci::response::CheckTx` comain type.

* The `Code` enum is more useful in idiomatic Rust

**Comment by thanethomson** [comment]
> In the [response struct](https://github.com/informalsystems/tendermint-rs/pull/1204/files#diff-8b372f30a4017d2a935c3db771835904c928aa48fced8fd30e55c8890581c8d2R43) for `/broadcast_tx_commit`, do we care to change the `check_tx` and `deliver_tx` fields to the corresponding domain types from the `tendermint` crate? Serde for `TxResult` reflects some quirks that may be only relevant for this endpoint, and also features the `mempool_error` field which is consciously omitted from the `abci::response::CheckTx` domain type.

The `mempool_error` field actually should be in `abci::response::CheckTx`. It's relevant to Tendermint v0.34.21+.

I'd say we should use the domain types as far as practically possible.

> The `Code` enum is more useful in idiomatic Rust than an integer. It explains itself in match contexts, it enforces the convention, and even has the same size as an `u32`. Would it make sense to promote it into the idiomatic types in `tendermint`?

Are you referring to the `Code` type defined in `tendermint-rpc`? I seem to remember @hdevalence preferring native Rust types. But for `Code` specifically it makes sense to me to promote it to the `tendermint` crate. Would this then be added to the `abci` module and used throughout that module?

**Comment by mzabaluev** [comment]
> The `mempool_error` field actually should be in `abci::response::CheckTx`. As per the [comment in the file](https://github.com/informalsystems/tendermint-rs/blob/00401ae253ab891cdeedf9932d90c3111fe1aaf9/tendermint/src/abci/response/check_tx.rs#L37), it shouldn't be set by the ABCI application. But what about when deserializing it via the RPC? Does it get returned via the RPC at any point?

It probably does in the response for `/broadcast_tx_commit`. If we consider the domain types as unified representation for both protobuf and RPC data, I should change the fields' type from the custom `TxResult` struct to `CheckTx`/`DomainTx`, add the optional field to `CheckTx`, and deal with the possible JSON quirks.

> Are you referring to the `Code` type defined in `tendermint-rpc`? I seem to remember @hdevalence preferring native Rust types. But for `Code` specifically it makes sense to me to promote it to the `tendermint` crate. Would this then be added to the `abci` module and used throughout that module?

Yes, I did that as part of #1204.
