### ISSUE TITLE
abci: Change hashes' type from `bytes::Bytes` to `tendermint::Hash`

### ISSUE THREAD

**Issue by thanethomson** [informalsystems/tendermint-rs#1095]
Version(s) of tendermint-rs: `master`

### Description

Related to #1090.

At the moment, several data structures in the `tendermint` crate's `abci` module have `hash` members of type `bytes::Bytes` (e.g. [`BeginBlock`](https://github.com/informalsystems/tendermint-rs/blob/33a48411a080692b3b962330d9f4492829a25c60/tendermint/src/abci/request/begin_block.rs#L20)). I'd like to rather make these of type [`tendermint::Hash`](https://github.com/informalsystems/tendermint-rs/blob/33a48411a080692b3b962330d9f4492829a25c60/tendermint/src/hash.rs#L27).

We can easily provide a conversion for non-empty hashes to `bytes::Bytes`.

cc @hdevalence 

### Definition of "done"

When all `hash` fields in structs in the `tendermint::abci` module are of type `tendermint::Hash`.

**Comment by mzabaluev** [comment]
Questions:

- The response structures `Info` and `InitChain` implement `Default` (`Info` also defaults the missing field values to the ones provided by the `Default` impl). If we change the app hash fields to `AppHash`, is it OK to have the default value of an empty byte array, like it already is de-facto?
- The `hash` field of `Snapshot` is documented as an arbitrary value compared by equality, so the semantics for neither `tendermint::Hash` nor `tendermint::AppHash` obviously apply. I think it's ok to leave it as `Bytes`.
