### ISSUE TITLE
Upgrade (or replace) *ring*

### ISSUE THREAD

**Issue by tarcieri** [informalsystems/tendermint-rs#11]
The *ring* crate (BoringSSL crypto primitives wrapped in Rust) is two versions out-of-date (currently 0.14, latest 0.16), and unfortunately like most other Rust crates, does not allow two versions to be linked simultaneously. I just updated Signatory and yubihsm-rs to use *ring* 0.16, but they're presently incompatible with the KMS due to the older version used by this crate:

```
$ cargo test --all --all-features -- --test-threads 1
    Updating crates.io index
error: failed to select a version for `ring`.
    ... required by package `yubihsm v0.27.0`
    ... which is depended on by `tmkms v0.6.3 (/Users/bascule/src/tmkms)`
versions that meet the requirements `^0.16` are: 0.16.6, 0.16.5, 0.16.4, 0.16.3, 0.16.2, 0.16.1, 0.16.0

the package `ring` links to the native library `ring-asm`, but it conflicts with a previous package which links to `ring-asm` as well:
package `ring v0.14.0`
    ... which is depended on by `tendermint v0.10.0`
    ... which is depended on by `tmkms v0.6.3 (/Users/bascule/src/tmkms)`

failed to select a version for `ring` which could resolve this conflict
```

All *ring* is used for is the ChaCha20Poly1305 implementation, which for me it seems like a particularly heavyweight dependency if we're only using it for that.

I've been contributing to the [`chacha20` crate](https://github.com/RustCrypto/stream-ciphers) as part of RustCrypto stream ciphers, which provides a potential replacement.

**Comment by tarcieri** [comment]
I released a full [`chacha20poly1305` crate](https://crates.io/crates/chacha20poly1305).

I'd say it's a bit "bleeding edge" to swap out immediately, but I know some people who want to play with it, so I'll let you know how that goes.

**Comment by xla** [comment]
The dependency was removed in a47430a7e3bbc5ca6d70a9d895d2b95c5f4992f7.
