### ISSUE TITLE
Light Client Spec related follow up

### ISSUE THREAD

**Issue by ebuchman** [informalsystems/tendermint-rs#111]
Replacement for elements of #96 more specific to specification. These need to be updated synchronously with the spec:

- [ ] capture the validation functions more explicitly in the spec and align with their use in the code
- [ ] redundant check for sigs (https://github.com/interchainio/tendermint-rs/pull/84#discussion_r358018987, https://github.com/tendermint/spec/pull/61#discussion_r358015568)
- [x] Improve naming of variables like `h1_xxx` and `h2` (https://github.com/interchainio/tendermint-rs/pull/100#discussion_r360342976, https://github.com/interchainio/tendermint-rs/pull/100#discussion_r36034392)
- [x] how to get latest height from a node? use height=0 ? Could get rid of get_smaller_or_equal (https://github.com/interchainio/tendermint-rs/pull/100#discussion_r360470376)
- [ ] improve logic of check_support to better clarify the 3 conditions: ok (update state), real error (faulty node or system), not-enough-voting-power (not real error, just need to bisect)
- [x] possible move validity checks from check_support to valdiate_vals_and_commit ...
- [x] add a single function that can be called by IBC that doesn't use a requester but otherwise does all checks necessary to update the store with a new trusted state. Ideally this function can be used by a function that does use the Requester

**Comment by ebuchman** [comment]
Alot of this was addressed on the Rust side in #114

**Comment by ebuchman** [comment]
These may be obsoleted by now but we should double check

**Comment by brapse** [comment]
All these  requirements look implementation specific except the last one which will be better captured by a standalone issue @milosevic is working on. Closing for now but feel free to re-open with clarifications.
