### ISSUE TITLE
Add document about how to run from binary.

### ISSUE THREAD

**Issue by scalalang2** [informalsystems/tendermint-rs#1146]
Hi, I wanna contribute this project.
But I couldn't find where I should start.

If there is a document describing how to run tendermint from binary. It would be very helpful.

thx.

**Comment by thanethomson** [comment]
This repo does not contain Tendermint, for Tendermint please see https://github.com/tendermint/tendermint/

tendermint-rs is a client framework that allows you to interact with Tendermint (via the RPC, ABCI, etc.).
