### ISSUE TITLE
bump k256 to 0.11

### ISSUE THREAD

**Issue by tomtau** [informalsystems/tendermint-rs#1153]
Version(s) of tendermint-rs: v0.23.x

### What went wrong?

The old version blocks upgrading it in cosmrs: https://github.com/cosmos/cosmos-rust/pull/228#issuecomment-1127916960

### Steps to reproduce

create a crate that depends on tendermint-rs and tries to use the latest version of k256 at the same time (directly or via other dependencies) 

### Definition of "done"

a new version of v0.23 that upgraded the dependency

**Comment by thanethomson** [comment]
Done in #1154
