### ISSUE TITLE
Support for HTTP Basic authentication in HTTP and WebSocket RPC clients

### ISSUE THREAD

**Issue by romac** [informalsystems/tendermint-rs#1169]
Version(s) of tendermint-rs: 

### Summary

Add support for [HTTP Basic authentication](https://datatracker.ietf.org/doc/html/rfc7617) in HTTP and WebSocket RPC clients.

### Problem definition

On the [Hermes](https://github.com/informalsystems/ibc-rs), we have heard a request from some operators to allow them to connect to a full node protected by HTTP Basic authentication.

[We initially thought](https://github.com/informalsystems/ibc-rs/issues/2459) that simply embedding the username and password in the RPC/WebSocket URL (eg. `http://username:password@example.com:1234`) would work [but it does not](https://github.com/informalsystems/ibc-rs/issues/2459#issuecomment-1197823813).

It seems like [`hyper`](https://lib.rs/hyper) does not automatically parse and use the username/password embedded in the URL. Instead, we have to manually add an `Authorization` header to the request.

Same thing with ([`async-`](https://lib.rs/async-tungstenite))[`tungstenite`](https://lib.rs/tungstenite), we have to manually set the `Authorization` header when building the initial HTTP request that upgrades the connection to WebSocket.

### Proposal

Implement support for HTTP Basic authentication for the HTTP and WebSocket clients in `tendermint-rpc`.

### Acceptance criteria

1. Both the HTTP and WebSocket clients can connect to a node protected by HTTP Basic authentication.
2. Hermes can connect to a node protected by HTTP Basic authentication. See [how to reproduce this](https://github.com/informalsystems/ibc-rs/issues/2459#issuecomment-1197823813) on the linked issue.

**Comment by thanethomson** [comment]
Closed by #1170
