### ISSUE TITLE
`main` branch has diverged from `v0.23.x`

### ISSUE THREAD

**Issue by romac** [informalsystems/tendermint-rs#1196]
### What went wrong?

It seems like the `v0.23.x` and `main` branches have recently diverged.

As you can see below, both branches have commit `590a0383` as a common ancestor. After that, they diverge. This means that `main` does not include some of the changes released in `v0.23.9`.

```
❯ git lg main | head -n 9
2f2e8686 - (HEAD -> main, origin/main, origin/HEAD) Do not generate well-known protobuf types (#1189) (2 weeks ago) <Mikhail Zabaluev>
88713235 - ci/docs: Update `master` references to `main` (#1190) (2 weeks ago) <Thane Thomson>
21e056cb - Derive Eq to appease clippy (#1191) (2 weeks ago) <Thane Thomson>
9b9ed446 - Add Tendermint Core compatibility note in readme (#1178) (7 weeks ago) <Thane Thomson>
dda92450 - Initialize the `main` branch (#1172) (7 weeks ago) <Thane Thomson>
590a0383 - v0.23.x: Add support for HTTP Basic authentication to HTTP and WebSocket RPC clients (#1170) (7 weeks ago) <Romain Ruetschi>
2426a65f - Bump async-tungstenite to 0.17 (#1167) (8 weeks ago) <Mikhail Zabaluev>
a2b33f6f - Add more `/abci_info` test fixtures (#1164) (8 weeks ago) <Mikhail Zabaluev>
8e51941f - (tag: v0.23.8) Release v0.23.8 (#1162) (9 weeks ago) <Thane Thomson>
```

```
❯ git lg v0.23.9 | head -n 8
a557ee73 - (tag: v0.23.9, origin/v0.23.x, v0.23.x) Release v0.23.9 (#1177) (7 weeks ago) <Thane Thomson>
7f547265 - Update Prost version to v0.11 (#1171) (7 weeks ago) <Thane Thomson>
717f680e - Add debug! trace for the outgoing RPC request (#1173) (7 weeks ago) <Romain Ruetschi>
9dc78345 - Pin `time` to <0.3.12 to ensure we stay no-std compatible (#1174) (7 weeks ago) <Romain Ruetschi>
590a0383 - v0.23.x: Add support for HTTP Basic authentication to HTTP and WebSocket RPC clients (#1170) (7 weeks ago) <Romain Ruetschi>
2426a65f - Bump async-tungstenite to 0.17 (#1167) (8 weeks ago) <Mikhail Zabaluev>
a2b33f6f - Add more `/abci_info` test fixtures (#1164) (8 weeks ago) <Mikhail Zabaluev>
8e51941f - (tag: v0.23.8) Release v0.23.8 (#1162) (9 weeks ago) <Thane Thomson>
```

### Possible cause

@thanethomson made the following observation:

> I suspect some of the PRs that targeted v0.23.x explicitly haven't yet been ported to main. Specifically:
> - https://github.com/informalsystems/tendermint-rs/pull/1174
> - https://github.com/informalsystems/tendermint-rs/pull/1173
> - https://github.com/informalsystems/tendermint-rs/pull/1171
> - https://github.com/informalsystems/tendermint-rs/pull/1177

### Steps to reproduce

1. `$ git clone https://github.com/informalsystems/tendermint-rs`
2. `$ git log --oneline main`
3. `$ git log --oneline v0.23.x`

### Definition of "done"

The PRs listed above are merged/backported to the `main` branch.

**Comment by thanethomson** [comment]
Looking at this again now, I initially thought that the PRs hadn't been merged, but they actually have :slightly_smiling_face: Sorry for the confusion here! The reason for the divergence in the Git histories is that, in #1172, I manually resolved the differences.

What I would recommend here is that we:
1. Merge #1195 
2. Bump Tendermint Core support to v0.34.21 (the latest release in the v0.34 series)
3. Cut a v0.25.0 release to free users of the need to pin their dependencies
4. Deprecate support for the `v0.23.x` branch

**Comment by romac** [comment]
Now that v0.25.0 is out, we can close this I think?
