### ISSUE TITLE
Add more complete usage docs for Query

### ISSUE THREAD

**Issue by SeedyROM** [informalsystems/tendermint-rs#1210]
### Description

I bashed my head for over an hour before I realized that you didn't need to create a `Query` with `::from(EventType)`. 

I had to search GitHub to find this use case [here](https://github.com/cosmos-george/ibc-rs/blob/b09ff9d7aa19c4162cdb3abcbf4c00b5ed744f15/relayer/src/chain/cosmos/query.rs#L25-L28).

### Definition of "done"

Add an example of `Query::eq`, `Query::gte` etc to the doc comments.

**Comment by thanethomson** [comment]
Have you seen the [docs](https://docs.rs/tendermint-rpc/0.25.0/tendermint_rpc/query/struct.Query.html)?
