### ISSUE TITLE
Trait-based cryptographic routines API to delegate implementation to downstream crates

### ISSUE THREAD

**Issue by blasrodri** [informalsystems/tendermint-rs#1213]
### Description

The goal is to be able to introduce an abstraction that encapsulates a set of everyday cryptographic operations needed
which do not necessarily share the exact underlying implementation details. This is precisely the case when we want to extend the functionality of the `Light Client Verifier` to support different light clients. Ideally, this could be used within any chain to verify the state of any other chain.

Based on [this pr/discussions](https://github.com/informalsystems/tendermint-rs/pull/1138) we've identified a few elements that we want to resolve:

- an agreed-upon interface (see below for a proposed one by @tony-iqlusion)
- reduce or eliminate the number of dependencies that are introduced
- be generic enough on the definition of methods/types so that we're not constraint to a specific implementation (see the [discussion](https://github.com/informalsystems/tendermint-rs/pull/1138#discussion_r901787307) about returning a boolean in the signature verification)

Proposed interface;

```rs
// https://github.com/informalsystems/tendermint-rs/pull/1138#issuecomment-1161835971

use digest::FixedOutput;
use digest::{consts::U32, Digest};
use tendermint::signature::Signer;
use tendermint::signature::Verifier;

pub trait CryptoProvider {
    type Sha256: Digest + FixedOutput<OutputSize = U32>;

    type EcdsaSecp256k1Signer: Signer<k256::ecdsa::Signature>;
    type EcdsaSecp256k1Verifier: Verifier<k256::ecdsa::Signature>;

    type Ed25519Signer: Signer<ed25519::Signature>;
    type Ed25519Verifier: Verifier<ed25519::Signature>;
}

```

### Definition of "done"

The trait is merged into the main branch, all tests are passed, and there is an external implementation of the trait 
for another light client that is successfully implemented using this interface.

**Comment by adizere** [comment]
Copying @thanethomson and @mzabaluev as potentially having feedback on this API. Thanks Blas for shepherding this!

**Comment by blasrodri** [comment]
I [drafted an implementation](https://github.com/informalsystems/tendermint-rs/pull/1214) of the trait for something similar to what Seun initially proposed. At least this proves that the design of the `CryptoProvider` is generic enough for us.

**Comment by mzabaluev** [comment]
The design looks good to me. It enshrines `digest` (rust-crypto) as the framework that the host must implement the crypto routines through, but tendermint already depends on `signature` and most implementations in practice are from rust-crypto as well.

**Comment by mzabaluev** [comment]
An update: I have discarded the `CryptoProvider` super-trait in #1238.

All crypto functions are available for an alternative implementation in terms of `digest` and `signature` traits. We only provide some type aliases and utility traits where the rust-crypto API is being more difficult to use than it should be.

**Comment by blasrodri** [comment]
🎊🎊❤️
