### ISSUE TITLE
Add constructor to `abci::tag::{Key, Value}`

### ISSUE THREAD

**Issue by plafer** [informalsystems/tendermint-rs#1217]
### Description
Currently, `Key` and `Value` can only be built with `FromStr`. When we have a `String`, we are forced to do `let key: Key = string.parse().unwrap()` (e.g. [here](https://github.com/cosmos/ibc-rs/blob/144f1bf5b1cad816cdf291444af795af0e5f01f7/crates/ibc/src/core/ics03_connection/events.rs#L38)). 

It would make it cleaner to have a `fn new(s: String) -> Self` constructor.

### Definition of "done"
`Key` and `Value` have a `fn new(s: String) -> Self` constructor.

**Comment by tony-iqlusion** [comment]
If there's no invariant being enforced, you might as well make the inner `String` member of the newtype tuple struct `pub`, rather than adding an infallible constructor.

**Comment by mzabaluev** [comment]
#1204 did away with these types.
