### ISSUE TITLE
Convert fallible From implementations to TryFrom

### ISSUE THREAD

**Issue by xla** [informalsystems/tendermint-rs#123]
Currently there are a handful of cases where the `From` trait is implemented and the implementation can panic. This is usually addressed with a conversion to a `TryFrom` implementation. See 71f0cd3 and https://rust-lang.github.io/rust-clippy/master/index.html#fallible_impl_from

**Comment by Liamsi** [comment]
Some of these Froms aren't used anywhere. Whoever tackles this might also consider removing the impls.

**Comment by tarcieri** [comment]
Which ones? It’d be good to make sure the KMS isn’t using them before removing them.

You can always add a temporary `[patch.crates-io]` to the KMS’s Cargo.toml pointing it at a local path to double check that.

**Comment by thanethomson** [comment]
Is this still relevant? Looking through the codebase now, I don't see any instances where we're disabling the `fallible_impl_from` lint, and I think there's one `From` impl that calls `unwrap()` internally (converting a `u64` to an `i64`) and there's a TODO above it to fix it.
