### ISSUE TITLE
Unexpected token

### ISSUE THREAD

**Issue by shanithkk** [informalsystems/tendermint-rs#1286]
### What went wrong?
While using ibc-rs , build failing due to 
``` 
/root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tendermint-0.29.1/src/abci/response/begin_block.rs:6:20

#[doc = include_str!("../doc/response-beginblock.md")] 
```

``` 
/root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tendermint-0.29.1/src/abci/response/check_tx.rs:8:20

#[doc = include_str!("../doc/response-checktx.md")] 
```
<img width="1028" alt="Screenshot 2023-03-20 at 6 16 57 PM" src="https://user-images.githubusercontent.com/59169878/226343800-4d14db72-0347-471e-be2c-a1b1bacd3023.png">

**Comment by romac** [comment]
@shanithkk Did you figure out what happened here, and how did you fix it?

**Comment by romac** [comment]
@shanithkk What exact steps did you follow to get this error?

**Comment by mzabaluev** [comment]
This is fixed by updating `syn@2` and `proc-macro2` in the dependency tree to the latest versions, released today. Running `cargo update` in the workspace should be enough in most cases.
I guess there was a regression in the proc macro framework, and it's been fixed now.

**Comment by shanithkk** [comment]
Thank you @mzabaluev
