### ISSUE TITLE
Can not generate tendermint-proto from source with buf dependencies

### ISSUE THREAD

**Issue by mzabaluev** [informalsystems/tendermint-rs#1289]
### Description

Originally reported as https://github.com/cometbft/cometbft/issues/565

tendermint-proto-compiler needs to be able to process buf dependencies in the `buf.lock` file in order to fetch third-party
protobuf modules used by CometBFT proto module source in releases starting from 0.37.0.
For #1193 I have scrounged by generating off the `v0.37.0-alpha.1` release and checking that the proto source has not changed between then and the eventual 0.37.x releases, but to adapt to any future changes we need to adapt to the buf way of managing protobuf dependencies.

### Definition of "done"

The tool that's used to generate code for tendermint-proto (either t-p-compiler or, if you feel ambitious, switch completely to buf.build) can deal with the buf dependencies in CometBFT releases since `v0.37.0`.

**Comment by tony-iqlusion** [comment]
We're dealing with a similar issue on cosmos-rust: https://github.com/cosmos/cosmos-rust/issues/318

So far we modified our `proto-build` to shell out to `buf`, however `protoc-gen-prost` looks promising: https://github.com/neoeinstein/protoc-gen-prost

**Comment by mzabaluev** [comment]
I'm implementing it as a shell-out as well, to have a tendermint-proto-compiler that can work with older v0.34.x checkouts as well as the new v0.37.x.

We will switch to full-on `buf` for generation and transition to using [versioned cometbft protos](https://github.com/cometbft/cometbft/pull/495) as a source at a later time.
