### ISSUE TITLE
Tendermint doesn't creates block in kv example

### ISSUE THREAD

**Issue by Iamknownasfesal** [informalsystems/tendermint-rs#1336]
### What went wrong?

Tendermint doesn't creates block in kv example. 

![image](https://github.com/informalsystems/tendermint-rs/assets/39006465/08dca02f-b6e0-4a49-92ff-dbbd53720e2e)

### Steps to reproduce

Just start the kv example included in /abci/README.md

### Definition of "done"

Tendermint should start to create blocks and start the rpc.

**Comment by thanethomson** [comment]
What version of tendermint-rs are you using? And are you using CometBFT or Tendermint Core, and which version?

**Comment by Iamknownasfesal** [comment]
I am using github as the version(git = "..."), and i am using tendermint core. Which is version 0.34.21

**Comment by thanethomson** [comment]
The `tendermint-abci` crate on `main` only supports the latest version of CometBFT, which is v0.38 (currently a release candidate).

**Comment by Iamknownasfesal** [comment]
> The `tendermint-abci` crate on `main` only supports the latest version of CometBFT, which is v0.38 (currently a release candidate).

Thanks for the reply, it works like a charm. Have a great day!
