### ISSUE TITLE
Complete P2P implementation

### ISSUE THREAD

**Issue by VegeBun-csj** [informalsystems/tendermint-rs#1347]
Will this project achieve complete tendermint P2P functionality in the future (which is completely corresponding to the tendermint P2P in the Go language version)? Currently, it seems only implements the function of `secret connection`, but there are still many things that are missing

**Comment by VegeBun-csj** [comment]
@brapse @tarcieri @xla @hdevalence hello guys, cc. Can we discuss it?

**Comment by xla** [comment]
Unlikely, given it isn't a priority.

**Comment by VegeBun-csj** [comment]
@xla. Currently, if Tendermint Rust only implements the type without implementing a node, it will be meaningless. Currently, only the Tendermint P2P in the Go language is fully implemented. To be honest, Tendermint-Rust has a lot of gaps to fill.

**Comment by hdevalence** [comment]
It's not meaningless, we built a whole blockchain using it. The crate provides common data types for modeling Tendermint/CometBFT data, and that's very valuable.
