### ISSUE TITLE
CI: switch to Github Actions?

### ISSUE THREAD

**Issue by Liamsi** [informalsystems/tendermint-rs#135]
[Github Actions](https://github.com/features/actions) is an alternative to circleci. It looks worth exploring! Things like code coverage and uploading to codecov.io looks much simpler for instance (it's a bit like [circleci's](https://circleci.com/orbs/?gclid=EAIaIQobChMIs4aGsKOp5wIVieN3Ch2qBwzxEAAYASAAEgIy4_D_BwE) [orbs](https://circleci.com/orbs/registry/orb/glotrade/rust) but integrated into github; also the snippets are hosted here on this platform)

Discussion started here:
https://github.com/interchainio/tendermint-rs/pull/134#issuecomment-579710445

**Comment by marbar3778** [comment]
@ebuchman @xla what you are thoughts on this? If people are up for the change, I'd love to make a contribution to the project.

**Comment by tarcieri** [comment]
I’ve moved most of my projects over. The UX is much better, and `actions-rs` is great

**Comment by Liamsi** [comment]
@marbar3778 at least I don't see a reason not to open a PR. I think it will also clarify a few things (e.g. performance, configurability) and make the discussion less abstract.

**Comment by tarcieri** [comment]
@marbar3778 make sure to check out https://github.com/actions-rs if you haven't already seen it

**Comment by marbar3778** [comment]
I have a branch here: https://github.com/marbar3778/tendermint-rs/pull/1 just need to figure out the codecov part but everything else looks good. Once its fixed ill open the PR against this repo

**Comment by Liamsi** [comment]
Awesome! The codecov part looks seemingly easy with this: https://github.com/marketplace/actions/rust-grcov
although, as always the devil is (or might be) in the details: https://github.com/actions-rs/grcov/issues/3
The good thing about GA is that one can read through the code and understand what is going on in the background (in this case TypeScript)

**Comment by tarcieri** [comment]
`grcov` + `codecov` works fine

**Comment by greg-szabo** [comment]
Awesome work Marko, thanks!
