### ISSUE TITLE
The null `value` field of `EventAttribute` should be allowed

### ISSUE THREAD

**Issue by mzabaluev** [informalsystems/tendermint-rs#1375]
An indexer ran into null `value` field of `EventAttribute`, preventing a service from indexing events and resulting in downtime. The exact error was `serde invalid type: null`.

_Originally posted by @daniel-savu in https://github.com/informalsystems/tendermint-rs/issues/1216#issuecomment-1802436901_

**Comment by mzabaluev** [comment]
The OpenAPI of the RPC interface does not allow for null-valued `value` fields, by omission of `nullable` on the appropriate schema. But this may be more about what event data the application is allowed to produce in practice. I don't see any checks forbidding null values in the code of CometBFT node. So I think the tendermint-rs implementation should tolerate nulls as well.

**Comment by daniel-savu** [comment]
Thank you for the quick follow up @mzabaluev! 

To answer your question about the Tendermint version, I believe the chain is using 0.34+. 

I'm not a Go developer but this is what I gather from the `go.mod` file: https://github.com/neutron-org/neutron/blob/51ecb6b0466077abd4bd16b3e5746aec150608c8/go.mod#L29

**Comment by mzabaluev** [comment]
> I believe the chain is using 0.34+.

Then you also need to use the correct compatibility mode with your tendermint-rpc client, otherwise your event data will be garbled (sorry for breaking this as we moved beyond 0.34; by 1.0 we should [get past this](https://github.com/cometbft/cometbft/issues/75)). 

I have just realized that our `WebSocketClient` documentation fails to include the builder API, but the code of the `tendermint-rpc` CLI binary can provide [an example](https://github.com/informalsystems/tendermint-rs/blob/707d2830e077e44148baad75e345936d897810b0/rpc/src/client/bin/main.rs#L300) of dynamic mode discovery. You may just need to use the specific `CompactMode` if the nodes you connect to all use a specific CometBFT version.

**Comment by daniel-savu** [comment]
Appreciate the heads up! Oddly enough, things have been running fine without `CompatMode::V0_34` but we'll keep a close eye on it
