### ISSUE TITLE
Light Client minor improvements

### ISSUE THREAD

**Issue by ebuchman** [informalsystems/tendermint-rs#138]
Follow up to #110 Types:
- [ ] memoize results of methods that don't take args, eg. `.hash()` (https://github.com/interchainio/tendermint-rs/issues/96#issuecomment-567003346)
- [ ] introduce a simple event type and let bisection function take a closure that will fire events. this can be used for logging so we don't need a print statement or logger inside the functions

Also follow up to PR review:
- [x] https://github.com/interchainio/tendermint-rs/pull/132#pullrequestreview-351913583

**Comment by ebuchman** [comment]
Possibly break this up into two issues. Memoizing isn't important for https://github.com/informalsystems/tendermint-rs/milestone/1 but some good form of logging probably is

**Comment by brapse** [comment]
It isn't clear what the motivation or expectation is here.

Is it possible that we want to know what blocks were part of a verification path? In which case this might be fulfilled by the `tracing` feature which is already landed:

https://github.com/informalsystems/tendermint-rs/blob/740cb66e25ea38ac6b545bc9b4f9b294dcc23277/light-client/src/state.rs#L32-L42

If not can it would be great to update the description of this issue with what we want and why.

**Comment by ebuchman** [comment]
I think we can close for now
