### ISSUE TITLE
Add the possibility to override User-Agent for queries

### ISSUE THREAD

**Issue by freak12techno** [informalsystems/tendermint-rs#1425]
### Description

Required for https://github.com/informalsystems/hermes/issues/3979.

TLDR: there should be a way for the library users', including Hermes, to override the User-Agent header for all the queries such an app does, so it would be easier for the node owners to understand which app is doing which queries, given that the app overrides User-Agent using this feature.

### Definition of "done"

A library provides a way to specify a custom User-Agent when creating a HttpClient.

**Comment by freak12techno** [comment]
@romac can we bump tendermint-rs to be able to use the new version in hermes?

**Comment by romac** [comment]
I will release this by end of week and then we can bump tendermint-rs in Hermes and set an appropriate user agent.

**Comment by freak12techno** [comment]
@romac lovely. Can you ping me once it's done?
Also, feel free to assign me to https://github.com/informalsystems/hermes/issues/3979, I basically have already done it, except for a new things.
