### ISSUE TITLE
`Protobuf` trait enforces `From<Self>`

### ISSUE THREAD

**Issue by rnbguy** [informalsystems/tendermint-rs#1473]
#1456 makes the conversion between tendermint-rs's auto-compiled Google's `Duration` and `core::time::Duration` fallible in both direction.

But, the `Protobuf` trait requires `T: From<Self>`

https://github.com/informalsystems/tendermint-rs/blob/2f94e7f5346a094ec98e9019d0181815ccede7f1/proto/src/lib.rs#L105

To include the changes for `Duration` type, this should be refactored to:

```rs
 pub trait Protobuf<T: Message + TryFrom<Self> + Default> 
```

cosmos/ibc-rs#1376 describes a breakage because of this.

**Comment by rnbguy** [comment]
I explored the idea of the refactor. But it seems that, it makes `encode_vec` and `encode_length` methods infallible - which in turn makes `hash`, `sign_bytes` and similar methods in domain types infallible.

**Comment by romac** [comment]
Not a bug, this is by design. The bug is the fallible conversion introduced in https://github.com/informalsystems/tendermint-rs/pull/1456
