### ISSUE TITLE
rustfmt config: nightly and stable

### ISSUE THREAD

**Issue by liamsi** [informalsystems/tendermint-rs#153]
The config options introduces in https://github.com/interchainio/tendermint-rs/pull/121 are causing some confusion. Maybe we should revert them, or, simply wait until they hit stable and close this issue then. Until then I'll keep this here for context for cointributors: You can ignore the warnings below:
![image](https://user-images.githubusercontent.com/7441766/74264867-5c759980-4cf9-11ea-80c8-ee7fdf7f95a9.png)

**Comment by ebuchman** [comment]
Can we close this?

**Comment by liamsi** [comment]
OK for me.
