### ISSUE TITLE
Error handling ADR

### ISSUE THREAD

**Issue by liamsi** [informalsystems/tendermint-rs#160]
After chatting with @Shivani912, this comment here https://github.com/interchainio/tendermint-rs/issues/150#issuecomment-586148337 should probably be made into a short ADR instead. 

While at it, verify there are still places where this comment applies, mention in a sentence in the ADR  and modify the code too: https://github.com/interchainio/tendermint-rs/pull/158#issuecomment-588290556

**Comment by ebuchman** [comment]
Lets close this for #669
