### ISSUE TITLE
Require that light client datatypes are serializable

### ISSUE THREAD

**Issue by romac** [informalsystems/tendermint-rs#190]
I would like to add `Serialize` and `Deserialize` bound on the traits defined in the `tendermint::lite::types` module to help get rid of [some very ugly bounds](https://github.com/informalsystems/ibc-rs/blob/96ee56d7b1c731c982f8085b9441e62cce974c00/relayer/relay/src/store.rs#L64) in `ibc-rs`.

Those are required by the current persistent store implementation, which needs to be able to (de)serialize these datatypes with a binary encoding in order to store them in the underlying [`sled`](https://sled.rs) database.

I do not see any reason why datatypes implementing those traits would not be serializable, but if you do please correct me :)

We could work around the need for those trait bounds by extending them with our own traits in the `ibc-rs` crate, but that would only introduce more traits whereas I [feel](https://github.com/informalsystems/tendermint-rs/issues/174#issuecomment-600169273) we should perhaps go the other way.

**Comment by Liamsi** [comment]
That makes absolute sense IMHO. Note that some of the mentioned types which aren't traits but structs currently derive (De)Serialize from serde: e.g. `SignedHeader` and `TrustedState`.
