### ISSUE TITLE
RPC: AbciInfo.last_block_app_hash should be bytes instead of Hash

### ISSUE THREAD

**Issue by Liamsi** [informalsystems/tendermint-rs#192]
`last_block_app_hash` can be anything and isn't required to be an actual hash. This currently make the the integration tests fail as the [kvstore app](https://github.com/tendermint/tendermint/blob/43f3276d6f99b7e6647ff2f3dd93ce50ece53c09/abci/example/kvstore/kvstore.go#L117) returns `AAAAAAAAAAA=` for `last_block_app_hash` which doesn't correspond to a valid sha256 hash.

In current master:
https://github.com/informalsystems/tendermint-rs/blob/471542d60d542a8049c81286dff13ffa467300fc/tendermint/src/rpc/endpoint/abci_info.rs#L49
as well as the current 0.33 branch
https://github.com/informalsystems/tendermint-rs/blob/e4918c8289fabc0573525b07148f33bc22e4a7f1/tendermint/src/rpc/endpoint/abci_info.rs#L47-L53

**Solution:** change `last_block_app_hash` to `Vec<u8>`.  Compare https://github.com/informalsystems/tendermint-rs/pull/188 by @romac (where Header.app_hash is Vec<u8> already).

It would also be nice if `Hash:new` would annotate the error kind instead of just returning `Kind::ParseError` as it doesn't say what went wrong.

**Comment by ebuchman** [comment]
Seems this is fixed? Can we close?

**Comment by Liamsi** [comment]
Yes, the main point was resolved resolved: https://github.com/informalsystems/tendermint-rs/blob/14f09ba88ab65d733d21246f5b27763528e0cc55/tendermint/src/rpc/endpoint/abci_info.rs#L46-L47

This part wasn't:
> It would also be nice if Hash:new would annotate the error kind instead of just returning Kind::ParseError as it doesn't say what went wrong.

I still think we can still close this and improve the error message for `Hash::new` whenever need arises (or we can use this Vec<u8>-when-deserializing approach and err in tryFrom when transforming into the real type and err there).
