### ISSUE TITLE
Explore clippy rules and apply quality of life recommendations

### ISSUE THREAD

**Issue by ebuchman** [informalsystems/tendermint-rs#193]
This is an issue to track the work started in #122 cc @xla

**Comment by Liamsi** [comment]
It seems like in the change from circleci to github actions clippy is called in a less strict way than perviously. If I run it locally via:
`cargo clippy --all --all-targets -- -Dwarnings -Drust-2018-idioms` it often shows some errs that do not show up in CI. Would be good to start with this simple online change.

**Comment by thanethomson** [comment]
Is the goal here to effectively apply as many of the `clippy::pedantic` rules as possible?

And what's the "definition of done" for this issue? It seems a little vague.

**Comment by greg-szabo** [comment]
Definition of done, based on the issue: turn all clippy warnings into errors.

I understand that there's an underlying bigger work that happened here previously (to apply as many clippy rules as we can) but I don't see this work progressing forward right now and half-defined issues won't help it either.

I propose we close this issue when we close #406 and if/when we feel the need to improve our clippy settings again, open an issue with well-defined targets.
