### ISSUE TITLE
ABCI Merkle `Proof` struct does not match Go counterpart

### ISSUE THREAD

**Issue by romac** [informalsystems/tendermint-rs#198]
@ancazamfir uncovered what we think is a discrepancy between the way ABCI Merkle proofs are represented in this crate vs the Go implementation.

The `AbciQuery` datatype into which ABCI responses are deserialized* carries an optional `Proof`, which [is defined in this crate](https://github.com/informalsystems/tendermint-rs/blob/5844dc5c0faa537b4225c5221cd863285b97d8ce/tendermint/src/abci/proof.rs#L13) as a wrapper around a bytevector serialized as a hex-encoded string, whereas the corresponding struct in the Go code [is defined as an actual struct](https://github.com/tendermint/tendermint/blob/ccf53a22760c92a02f1f20ed24a7ec9f510d7c5d/crypto/merkle/merkle.pb.go#L94) with proof ops etc.

It is thus currently not possible to properly deserialize the result of ABCI queries when those carry a proof, [as shown in the tests](https://github.com/informalsystems/ibc-rs/pull/38/files#diff-60c428c0790e3ea2800d7dc19f35d00cR8) Anca included in [her PR](https://github.com/informalsystems/ibc-rs/pull/38) implementing a consensus state query for `ibc-rs`.

\* We should perhaps find a better name for that struct, since [it is used](https://github.com/informalsystems/tendermint-rs/blob/753cf3e52b93f7d2439514eb01a247e2fcf94244/tendermint/src/rpc/client.rs#L39) both for queries and their responses. Or perhaps the issue stems from the fact that those should be different datatypes?

**Comment by tarcieri** [comment]
I'm guessing this is another v0.33 incompatibility? (see #184)

**Comment by tomtau** [comment]
ABCI `Proof`  was structured that way before 0.33: https://github.com/tendermint/rust-abci/blob/aa163393f139b971f7935ad6afac4f542e1bb016/src/messages/merkle.rs

I guess it should be fine once the types are generated from canonical protobuf definitions
ref: https://github.com/informalsystems/tendermint-rs/issues/29#issuecomment-534102801

**Comment by ancazamfir** [comment]
Fixed in https://github.com/informalsystems/tendermint-rs/pull/206, in `tendermint/v0.33` branch. Thanks @Liamsi
