### ISSUE TITLE
Explore MIRAI annotations

### ISSUE THREAD

**Issue by tomtau** [informalsystems/tendermint-rs#200]
Given the awesome on work on verification (e.g. https://github.com/informalsystems/verification ), it may be worth exploring whether some of the key invariants could be extracted out into and verified in Rust code as pre/post contracts using MIRAI: 
https://github.com/facebookexperimental/MIRAI/blob/master/annotations/README.md
https://github.com/facebookexperimental/MIRAI#using-mirai-together-with-the-rust-design-by-contracts-crate

For more realistic examples, see the usage in Libra: https://github.com/libra/libra/commit/9883c387865d3c615652ce508b1bff62e91e2e27

**Comment by ebuchman** [comment]
Closing for #559
