### ISSUE TITLE
Add tendermint types needed by ibc to amino_types

### ISSUE THREAD

**Issue by liamsi** [informalsystems/tendermint-rs#203]
Looks like the (current) implementation of ibc uses amino and in the current rust implementation (ibc_rs) needs to be able decode these. It would be good if the concrete types that already live in tendermint-rs would have their prost / prost_amino annotated counterparts live in the tendermint-rs repo too instead of adding them to the ibc-rs repo. 
I'll add a amino_types.rs module to ibc-rs to unblock this: https://github.com/informalsystems/ibc-rs/issues/45 but as soon as this works we should move them into tendermint-rs and update the dependency on tendermint in ibc-rs.

Example types that should also allow serialization via amino or prost / protobuf are the `SignedHeader`, `ValidatorSet`. They are implicitly contained in the `latest_header` field here: 
https://github.com/informalsystems/ibc-rs/blob/b603ccc6a0ddeaa37caf3d78dded3374d4a7056d/modules/src/ics07_tendermint/client_state.rs#L11-L17

ref: #197

**Comment by ebuchman** [comment]
I think this will be taken care of in the upgrade to Tendermint Core v0.34 comptaibility eg #504, #527, #535, etc.
