### ISSUE TITLE
`broadcast_tx_commit` response data property can be null

### ISSUE THREAD

**Issue by sphw** [informalsystems/tendermint-rs#216]
Some responses to `broadcast_tx_commit` will have a value of `null` for the `data` field in both `check_tx` and `deliver_tx`. Right now the fields aren't marked optional so it leads to an error being thrown by Serde. This could be solved in two ways. The data field could be marked as `default` and Serde would handle this, or the field could simply be an optional

**Comment by Liamsi** [comment]
I really, really think we should use the proto files to generate the abci types instead of manually curate them (see discussions in #29)

**Comment by Liamsi** [comment]
Oh, this actually about the rpc types. Here, we need better integration tests. It seems that these edge cases often aren't tested properly.
