### ISSUE TITLE
light client optimization function for the IBC Relayer

### ISSUE THREAD

**Issue by ancazamfir** [informalsystems/tendermint-rs#240]
When running an IBC relayer, there are light clients running for the chains for which relaying is enabled. In one approach, these run periodically, downloading, verifying and storing headers in a trusted store.
The IBC relayer then uses these headers to update the consensus state of the on-chain IBC client.
Here are some details:
- light client has `n` headers `H(1), .., H(k), .., H(n)` in the trusted store for chain A, where `H(i)` and `H(i+1)` heights are not necessarily sequential. 
- on chain B, the IBC client for chain A has been previously updated with `H(k)`.
- the relayer needs to update the on-chain IBC client to `H(n)` and it may or may not need some or all of the intermediate headers `H(k+1),..,H(n-1)`.

I think it is possible to have a bisection variant that determines the minimum required intermediate headers that the relayer needs to use for the IBC client updates. Note that this bisection variant would not require any new header downloads, just the validator-set-trust verification over (some of) the trusted store headers .

(reason: the relayer pays transaction fees for the on-chain updates)

**Comment by ebuchman** [comment]
Why are the bisection needs of the IBC client different than that of the local client?

**Comment by ancazamfir** [comment]
Because we would "bisect" over the headers in the trusted store and not on the chain.  We want the headers to be stored and verified already so the relayer doesn't wait for the light client to retrieve header, verify, bisect, etc.

**Comment by ancazamfir** [comment]
The on-chain client updates are done by the relayer as part of other IBC datagram relaying. For example, the relayer may stay idle until an IBC related event (connection, channel, packet related) occurs. At that point, in the process of building the corresponding IBC datagram, the relayer may determine that the on-chain client on destination chain needs to be updated before the new IBC datagram is sent.
The relayer will then send two or more IBC datagrams, a number of `ClientUpdateMsg` datagrams and then the event related IBC datagram, e.g. `ConnOpenTryMsg`.

**Comment by ancazamfir** [comment]
One exception to the above, if no IBC related event occurs over `trusting_period`, the on-chain client needs to be updated, in this case only `ClientUpdateMsg`(s) will be send in the IBC transaction.

**Comment by ebuchman** [comment]
> Because we would "bisect" over the headers in the trusted store and not on the chain. We want the headers to be stored and verified already so the relayer doesn't wait for the light client to retrieve header, verify, bisect, etc.

Shouldn't the set of headers in the trusted store be the set of headers you need to relay to the other chain?

**Comment by ebuchman** [comment]
Oh I see, the other chain could have been updated independently and might need a different minimal set of headers than the one we have. So we need to expose a way to look back through our trusted set of headers and figure out which ones the other chain will need. This is strictly an optimization and something we can address later though, right? It's just a matter of needing to expose the functionality to do so through the API?

**Comment by ancazamfir** [comment]
yes and yes :)

**Comment by ancazamfir** [comment]
I have created an issue on ibc-rs as it already has its own  `update()`, manages store, invokes bisection, etc.: https://github.com/informalsystems/ibc-rs/issues/60
Closing this one.
