### ISSUE TITLE
CI: Code coverage broken

### ISSUE THREAD

**Issue by Liamsi** [informalsystems/tendermint-rs#250]
Looks like `no-landing-pads` was removed from nightly:
```
  process didn't exit successfully: `rustc - --crate-name ___ --print=file-names -Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Zno-landing-pads --crate-type bin --crate-type rlib --crate-type dylib --crate-type cdylib --crate-type staticlib --crate-type proc-macro --print=sysroot --print=cfg` (exit code: 1)
--- stderr
error: unknown debugging option: `no-landing-pads
```
It is currently used to call grcov: 
https://github.com/informalsystems/tendermint-rs/blob/3ec9f1092a533921637e8a39e5ea6bdb5a681cbd/.github/workflows/rust.yml#L97

Needs further investigation or this might be a good chance to switch to tarpaulin https://github.com/actions-rs/tarpaulin as suggested by @tarcieri in previous discussions.

**Comment by tarcieri** [comment]
IMO tarpaulin has more accurate (i.e. fewer false negatives) coverage analysis. I know some people who recently tried playing with switching from tarpaulin -> grcov and went back for the same reason.

**Comment by Liamsi** [comment]
closing in favour of #252
