### ISSUE TITLE
CommitSig Timestamp can be zero time

### ISSUE THREAD

**Issue by greg-szabo** [informalsystems/tendermint-rs#259]
**Go implementation**
In CommitSig, in the BlockIDFlagAbsent type, the Timestamp field is a Go "Zero value" (`0001-01-01T00:00:00Z`).

**ADR-025**
The Timestamp field in Absent signatures should be null or omitted.

**Current Rust implemenation**
Rust implemented the ADR.

**Problem**
Tendermint-Rust is incompatible with Tendermint-Go.

**Solution**
- [done #277](https://github.com/informalsystems/tendermint-rs/pr/277) Add a compatibility code to the Rust implementation.
- [todo] Add an issue to the Go repository
- [todo] Remove the compatibility code when the Go code adheres to ADR-025

Relevant discussion:
https://github.com/informalsystems/tendermint-rs/pull/196#discussion_r401027989

**Comment by greg-szabo** [comment]
Next step: open a Go issue and link it here. (I need to reproduce the issue in Go for them.)

**Comment by Liamsi** [comment]
This was resolved in https://github.com/informalsystems/tendermint-rs/pull/277

I think we should rather close this PR. If the changes are made in go (and there will be potenially more substantial changes in the light of https://github.com/tendermint/tendermint/pull/4857). Feel free to re-open this issue if you thinjk we should open an issue in amino or tendermint and link it here.
