### ISSUE TITLE
Further JSON test fixes required

### ISSUE THREAD

**Issue by Shivani912** [informalsystems/tendermint-rs#268]
**Context**
PR #267 introduces directory structure changes to the existing JSON tests. 

**Problem**
This requires us to change the way these tests are run in Rust code because the older files no longer exist. What we have currently is configured to read big JSON files that deserialize into a vector of `TestCase` and we loop over them to run our tests. But now, we have split all these huge JSON files into multiple files such that each JSON file is a single `TestCase`. Now that there are so many files, it is messy to read each file manually and run test over it. 

**Proposed Solution**
Configure Rust test to loop over these files instead of manually having to read each one of them.

**Comment by Liamsi** [comment]
I'll cherrypick the changes from #267 and delete the now obsolete test code. If there are new test-failures (e.g. https://github.com/informalsystems/tendermint-rs/pull/267#issuecomment-629222593), I'll "blacklist" those for now and fix them later.

**Comment by Liamsi** [comment]
From the description I was expecting that all these 4 tests fail:
./single_step/sequential/commit/one_third_vals_don't_sign.json
./single_step/sequential/commit/more_than_two_third_vals_sign.json
./single_step/skipping/commit/one_third_vals_dont_sign.json
./single_step/skipping/commit/more_than_two_third_vals_sign.json

Weirdly only the first currently fails.
