### ISSUE TITLE
Resolve "this last check is only necessary if we do full verification (2/3)" comment

### ISSUE THREAD

**Issue by greg-szabo** [informalsystems/tendermint-rs#281]
```
TODO: this last check is only necessary if we do full verification (2/3) but the
above checks should actually happen always (even if we skip forward)
```

The above comment was introduced `lite_impl/signed_header.rs` during the Tendermint v0.33 upgrade [in this PR](https://github.com/informalsystems/tendermint-rs/blame/0eae7236f1ef6ac8487f5aa6a6ec94cf63df25e7/tendermint/src/lite_impl/signed_header.rs#L136)

[During the code review](https://github.com/informalsystems/tendermint-rs/pull/199/files#r401987638), it was pointed out that it should go somewhere else.
Anton also commented on it [here](https://github.com/informalsystems/tendermint-rs/pull/196/files#r409502161).

During the CommitSig refactor it [came up again](https://github.com/informalsystems/tendermint-rs/pull/277) so I opened this issue to track it and eventually get rid of it for good.

**Comment by brapse** [comment]
Although this references a lot of context it is unclear how actionable this is. Can we please update the description to be a context free description of what the actual problem is and how it can be remedied?

**Comment by ebuchman** [comment]
This comment is in the `lite_impl` module which will be deprecated/deduplicated ala #342. This kind of issue (ie. checks in full verification that arent in the overlap/bisection verification) will be ultimately dealt with by #377 . So closing for those.
