### ISSUE TITLE
`BlockIdFlagNil` votes counted when verifying a commit

### ISSUE THREAD

**Issue by OStevan** [informalsystems/tendermint-rs#282]
Comparing the implementation of Light Client verification with the Go one, there is a difference in the calculation of the voting power for a commit.

Methods `verify_commit_full` and `verify_commit_trusting` in `lite/verifier.rs` use a method [`voting_power_in`](https://github.com/informalsystems/tendermint-rs/blob/afb11bf21fc3899edaf157b4f95e1b94a158215b/tendermint/src/lite_impl/signed_header.rs#L17) which sums up voting power for all validators in the commit which have a non absent vote.

Comparing this to the Go implementation in functions `VerifyCommit` and `VerifyCommitTrusting` in `types/validator_set.go` where voting power is counted by summing up only those which have a [`BlockIdFlagCommit`](https://github.com/tendermint/tendermint/blob/master/types/validator_set.go#L681) vote.

This then results in Rust implementation accepting commits which have no `BlockIdFlagCommit` votes but only `BlockIdFlagNil`.

**Comment by ebuchman** [comment]
Another bug in voting_power_in (TODO in the code), we need to not double count signatures from a validator!

Probably the function should be written to depend less on the ValidatorAddress in the vote, and instead iterate over the relevant validator set to get the pubkeys to verify the sigs with?

**Comment by ebuchman** [comment]
Weird, we're using a `signed_votes` method to get the votes in the `voting_power_in`, but I'm not sure I understand why - I think we can just loop over the CommitSigs, ignore the ones that are Absent or Nil, and only reconstruct the Vote (to get the signbytes) for the ones that are actually for the BlockID.

**Comment by romac** [comment]
Here's a draft PR which addresses those issues (aside from still having the validator address stored in the `Vote` struct): https://github.com/informalsystems/tendermint-rs/pull/306

It's a draft there's still a couple TODOs, and the method should likely be renamed/its signature should be changed to reflect the new behavior.

Most of logic and comments are taken from the Go code, so perhaps some attribution should be added as well.

**Comment by romac** [comment]
Oh, and the tests are failing because we need to adapt the call sites as well. So a very much WIP/draft PR but I just wanted to put it out there if anyone already has some feedback.
