### ISSUE TITLE
RPC integration tests failing on CI

### ISSUE THREAD

**Issue by romac** [informalsystems/tendermint-rs#304]
The RPC integration tests are currently failing on CI.

Affected PRs are:
- #302 ([job](https://github.com/informalsystems/tendermint-rs/pull/302/checks?check_run_id=742462716))
- #284 ([job](https://github.com/informalsystems/tendermint-rs/pull/284/checks?check_run_id=742259921))

Here's an excerpt from the build logs for #302:

<details>
<summary>Click to show log</summary>

```
running 11 tests

test rpc::abci_info ... ok
test rpc::abci_query ... ok
test rpc::block ... FAILED
test rpc::block_results ... ok
test rpc::commit ... FAILED
test rpc::blockchain ... FAILED
test rpc::genesis ... ok
test rpc::health ... ok
test rpc::net_info ... ok
test rpc::status_integration ... ok
test rpc::event_subscription ... FAILED

failures:

---- rpc::block stdout ----
thread 'rpc::block' panicked at 'called `Result::unwrap()` on an `Err` value: Error { code: ParseError, message: "Parse error. Invalid JSON", data: Some("invalid type: integer `1`, expected a string at line 8 column 19") }', tendermint/tests/integration.rs:73:26
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- rpc::commit stdout ----
thread 'rpc::commit' panicked at 'called `Result::unwrap()` on an `Err` value: Error { code: ParseError, message: "Parse error. Invalid JSON", data: Some("invalid type: integer `0`, expected a string at line 17 column 23") }', tendermint/tests/integration.rs:111:27

---- rpc::blockchain stdout ----
thread 'rpc::blockchain' panicked at 'called `Result::unwrap()` on an `Err` value: Error { code: ParseError, message: "Parse error. Invalid JSON", data: Some("invalid type: integer `1`, expected a string at line 11 column 23") }', tendermint/tests/integration.rs:95:31

---- rpc::event_subscription stdout ----
[tendermint/src/rpc/event_listener.rs:95] "We did not receive a valid JSONRPC wrapped ResultEvent!" = "We did not receive a valid JSONRPC wrapped ResultEvent!"
thread 'rpc::event_subscription' panicked at 'called `Result::unwrap()` on an `Err` value: Error { code: Other(-1), message: "Error (code: 0)", data: Some("received neither event nor generic string message") }', tendermint/tests/integration.rs:164:34

failures:
    rpc::block
    rpc::blockchain
    rpc::commit
    rpc::event_subscription

test result: FAILED. 7 passed; 4 failed; 0 ignored; 0 measured; 0 filtered out
```
</details>

**Comment by Liamsi** [comment]
Related comment: https://github.com/informalsystems/tendermint-rs/issues/120#issuecomment-634541018

I'll have a look.

**Comment by Liamsi** [comment]
This is actually also related: https://github.com/informalsystems/tendermint-rs/issues/305 

We first need to decide if we want to migrate and be on par with 0.34 as soon as it is releases and basically keep up to date with the changes in go-tendermint's master (because the docker images we are testing against are build from master).  

cc @ebuchman

**Comment by ebuchman** [comment]
Yes we should target v0.34 but we need some lead time so our tests shouldn't fail just because we're behind the latest breaking release. We should make sure the tests run against something stable ...

**Comment by Liamsi** [comment]
They are still failing now (prob. due to other reasons): https://github.com/informalsystems/tendermint-rs/runs/772419078#step:5:271
re-opening
