### ISSUE TITLE
Need access to block in `EventDataNewBlock`

### ISSUE THREAD

**Issue by ancazamfir** [informalsystems/tendermint-rs#308]
The IBC relayer subscribes for block notifications and on `EventDataNewBlock` it needs access to the block height only ...for now.
But content is not public:
https://github.com/informalsystems/tendermint-rs/blob/bcef28b55a83dc3917aeedc8acf6429108aead5c/tendermint/src/rpc/event_listener.rs#L193

Is there an access function I don't see?

**Comment by Liamsi** [comment]
> Is there an access function I don't see?

I don't think so. Maybe we should make all fields public here. I still need to work on the event subscription refactoring and ADR.
