### ISSUE TITLE
event_listener Web socket error

### ISSUE THREAD

**Issue by ancazamfir** [informalsystems/tendermint-rs#311]
IBC relayer event monitor, subscribed to Block and Tx events on gaia node, sees this error every ~27sec. It is issued from https://github.com/informalsystems/tendermint-rs/blob/bcef28b55a83dc3917aeedc8acf6429108aead5c/tendermint/src/rpc/event_listener.rs#L105
```
[/Users/ancaz/rust/tendermint-rs/tendermint/src/rpc/event_listener.rs:96] "We did not receive a valid JSONRPC wrapped ResultEvent!" = "We did not receive a valid JSONRPC wrapped ResultEvent!"
Jun 09 12:48:20.007 DEBUG relayer::event_monitor: Web socket error: Error (code: 0): received neither event nor generic string message (code: -1)`
```

**Comment by Liamsi** [comment]
Which tendermint version does this use?

**Comment by ebuchman** [comment]
Now that #516 is merged when we update ibc to use latest tendermint we should check that this is fixed. I expect it should be.

**Comment by romac** [comment]
> Now that #516 is merged when we update ibc to use latest tendermint we should check that this is fixed. I expect it should be.

I am currently doing this as part of https://github.com/informalsystems/ibc-rs/issues/90 and https://github.com/informalsystems/ibc-rs/issues/243

**Comment by ebuchman** [comment]
Note that the new websocket is only on master, its not in v0.16. Not sure if you're gunning for master all at once or doing an intermediary through v0.16

**Comment by romac** [comment]
I have to get some changes into tendermint-rs as part of this work, so I guess I am going to go for master directly.

**Comment by romac** [comment]
@ancazamfir Is this still an issue?

**Comment by ancazamfir** [comment]
Looks like it's fixed, I don't see this anymore. Thanks!
