### ISSUE TITLE
Event subscription ADR and refactor event_listener module

### ISSUE THREAD

**Issue by liamsi** [informalsystems/tendermint-rs#313]
https://github.com/informalsystems/tendermint-rs/blob/71d7e238a0fb4b5d7e9902875f09a0cf10ac4746/tendermint/src/rpc/event_listener.rs#L70-L71

https://github.com/informalsystems/tendermint-rs/blob/71d7e238a0fb4b5d7e9902875f09a0cf10ac4746/tendermint/src/rpc/event_listener.rs#L112-L115

https://github.com/informalsystems/tendermint-rs/blob/71d7e238a0fb4b5d7e9902875f09a0cf10ac4746/tendermint/src/rpc/event_listener.rs#L196-L197

Subscribe should return a stream of events tied to the particular query. Pretty much what the go-code returns on subscribe but "rust style". E.g. see: https://docs.tendermint.com/master/rpc/#/Websocket/subscribe

Furthermore, the current code only supports two events: 
https://github.com/informalsystems/tendermint-rs/blob/cc6a4cf5f241d14069972396927dd374d12af8cb/tendermint/src/rpc/event_listener.rs#L33-L34
While tendermint actually has more event types:
https://github.com/tendermint/tendermint/blob/6961c7e5d1f2a187bc5f77ac0056ce5ec5bf7ec6/types/events.go#L21-L24

also https://github.com/informalsystems/tendermint-rs/blob/cc6a4cf5f241d14069972396927dd374d12af8cb/tendermint/src/rpc.rs#L8
ref: #311

**Comment by thanethomson** [comment]
What level of granularity of event routing to subscribers is needed here? Do we need fine-grained routing to subscribers the way the [Go code handles it](https://github.com/tendermint/tendermint/blob/2ac5a559b4c88385e173b673d1f6250ff7c55263/libs/pubsub/pubsub.go#L65), or will matching purely based on event type (`tm.event`) suffice?

**Comment by liamsi** [comment]
Good question. I think ideally we would replicate the (fine-grained) go behaviour here. It just makes the most sense to me: a dev coming from tendermint go will immediately be familiar with the rust version and it's likely that you want to build (complex) queries and only receive the events for those for instance. 

On the other hand the current simpler approach was successfully used in GoZ and as far as I understand the main use case will be specific events in ibc. So if mimicking the go behaviour overcomplicates this we could go with a simpler variant as long as all use cases in ibc can be handled with it.

**Comment by xla** [comment]
As mentioned in this https://github.com/informalsystems/tendermint-rs/pull/476/files#r465102351 - I think we should take the opportunity and design a query system that fits the language and runtime.
