### ISSUE TITLE
[light-client] Guard against circular dependencies

### ISSUE THREAD

**Issue by brapse** [informalsystems/tendermint-rs#326]
In the case in which light client A is configured to sync to light client B while light client B is configured sync against Light Client A, the circular dependency might cause some weird behaviour depending on the additional peer lists of the respective light clients. This is a very rare case and would require pathological manual configuration of both. This issue is just meant to document this rare case and potentially serve as a gateway to new contributors 🙏

**Comment by ebuchman** [comment]
Not sure I understand this - what does it mean for one client to sync against another?

**Comment by ebuchman** [comment]
@brapse can you clarify? Or should we close?

**Comment by brapse** [comment]
Yes it's an edge case and can be closed.
