### ISSUE TITLE
Basic bisecting schedule logic can be simplified

### ISSUE THREAD

**Issue by milosevic** [informalsystems/tendermint-rs#333]
In the basic bisection schedule implementation, see

https://github.com/informalsystems/tendermint-rs/blob/184a1f9925f541473313efcd483c32cb913f8af9/light-client/src/components/scheduler.rs#L56-L75

lines 70 to 74 shouldn't be needed.

In my understanding,  There are only two scenarios in which basic_bisecting_schedule is called (in case verification of header failed), and they are covered by lines:

https://github.com/informalsystems/tendermint-rs/blob/184a1f9925f541473313efcd483c32cb913f8af9/light-client/src/components/scheduler.rs#L66-L69

Also trusted_height should always be smaller than target_height.

**Comment by ebuchman** [comment]
Similar to my comment in https://github.com/informalsystems/tendermint-rs/issues/294#issuecomment-639076639, some of which still applies

**Comment by romac** [comment]
Inlining https://github.com/informalsystems/tendermint-rs/issues/294#issuecomment-639076639:

> Also a note about the scheduler. It's a bit hard to read the bisection logic out of it. 
> 
> - Can we use single word variable names like `trusted`, `next`, and `target` to make this more readable in cases like this where it's obvious we're dealing with heights and no other types? 
> - The conditional block is hard to read. Can we clarify the cases somehow by relying on relationships that should always hold when verifying into the future, like (?) :
>    - trusted <= next
>    - trusted <= target
>    - next <= target
> - If the above conditions are true, it's hard to understand that last branch of the conditional (it would never trigger?)
> - How to reconcile previous point with need to schedule into the past? Split the schedule function in two ?

**Comment by ebuchman** [comment]
I think this has been completed? Let me know if not.
