### ISSUE TITLE
Don't add voting power of the same validator multiple times in voting_power_in

### ISSUE THREAD

**Issue by milosevic** [informalsystems/tendermint-rs#335]
There is a TODO already in the code: https://github.com/informalsystems/tendermint-rs/blob/184a1f9925f541473313efcd483c32cb913f8af9/light-client/src/operations/voting_power.rs#L38

**Comment by romac** [comment]
Addressed in #306 (024a73dadd15cd4d717253a1a902ad4af31297a6)
