### ISSUE TITLE
[rpc] crate follow-ups

### ISSUE THREAD

**Issue by xla** [informalsystems/tendermint-rs#339]
As leftovers from #338 we need to address to main points

* [x] crate documentation https://github.com/informalsystems/tendermint-rs/pull/338#discussion_r441742695
* [x] a satisfying solution to the now public serialisers: https://github.com/informalsystems/tendermint-rs/pull/338#discussion_r441768296
* [x] potentially make only endpoints available: https://github.com/informalsystems/tendermint-rs/issues/289#issuecomment-645719342

**Comment by yihuang** [comment]
It seems keeping the endpoint data types inside tendermint crate, can help keeping the serializers private.

**Comment by Liamsi** [comment]
> It seems keeping the endpoint data types inside tendermint crate, can also help keeping the serializers private.

@yihuang from your point of view and keeping the serializer helper methods aside, are their other good reasons to keep the rpc endpoints (or the whole module) inside the tendermint crate?

**Comment by yihuang** [comment]
> > It seems keeping the endpoint data types inside tendermint crate, can also help keeping the serializers private.
> 
> @yihuang from your point of view and keeping the serializer helper methods aside, are their other good reasons to keep the rpc endpoints (or the whole module) inside the tendermint crate?

I don't have other reasons for that, I think feature guarding is good too ;D

**Comment by ebuchman** [comment]
Given all the recent serialization work, can we close this @thanethomson @greg-szabo ?
