### ISSUE TITLE
Remove `AnonLightBlock` test helper

### ISSUE THREAD

**Issue by romac** [informalsystems/tendermint-rs#372]
Now that we are generating test cases using `testgen` (whose `LightBlock` type contains a `provider` field), we should be able to remove the [`AnonLightBlock` struct](https://github.com/informalsystems/tendermint-rs/blob/4c7e5d1afe22beeeb5f90aedfc686f4eda053640/light-client/src/tests.rs#L196-L199) and related code in `light-client/src/tests.rs`.

**Comment by ebuchman** [comment]
More concrete description here?
