### ISSUE TITLE
light-client: test against a real full node in CI

### ISSUE THREAD

**Issue by ebuchman** [informalsystems/tendermint-rs#373]
We should run the light node against a real full node in CI per https://github.com/informalsystems/tendermint-rs/issues/120#issuecomment-644173634

We already run the RPC integration tests against a local full node, but we're not running the light node against it. 

The first and simplest thing to do is to run the light-node against that full node. Since it will just be a 1 validator blockchain that doesn't change, this will not test much of the light-client functionality, but is more about ensuring the light-node init/config/process is working correctly and can sync with a real full node.

Future iterations could introduce a lot more complexity:
- talking to multiple full nodes (where one of the full nodes may be faulty or may serve a fork)
- enabling validator set changes on the chain (this would require other full nodes to actually be set up to be the new validators, even if the light node doesn't talk directly to them!)
- talking to remote full nodes from a live mainnet/testnet Gaia blockchain 

Since there's a lot to do re scoping the more complex set ups, let's start with the simplest for now.

**Comment by liamsi** [comment]
ref: https://github.com/tendermint/tendermint/pull/5087
Context: when new docker images for tendermint-go are published, it should simplify testing against CI slightly.

**Comment by ebuchman** [comment]
Hey is this done with #431?

**Comment by brapse** [comment]
Yeah this is done but made a follow up for the binary initiazation process specifically in #445.
