### ISSUE TITLE
Dev session to discuss TLA+ modeling

### ISSUE THREAD

**Issue by josef-widder** [informalsystems/tendermint-rs#378]
There are very interesting questions on modeling in TLA+ raised by @ancazamfir in #314 . @konnov and I are answering them in the PR, but it might be interesting to schedule a dev session to discuss this more broadly.

**Comment by ancazamfir** [comment]
Sorry I am late to react on this and the original issue. Anything we need to prepare? Or we review the comments? Should we schedule this during our regular dev sessions? If yes, I will check with Arianne for a slot.

**Comment by konnov** [comment]
I think the idea was just to get together for 1-2 hours and discuss the modeling issues that arise say in the light client spec, IBC, etc.

**Comment by josef-widder** [comment]
Yes, I think during a regular dev session makes sense. Some weeks ago, we discussed with @ebuchman and @milosevic that after we wrap up specs for deliverables (perhaps also at the end of a quarter) we discuss the specs, how they were written and why, etc. The goal would be to in the mid-term establish a "standard" or a common understanding how we would like to write specs.

**Comment by ancazamfir** [comment]
Ok, I will talk to Arianne and schedule one.

**Comment by ancazamfir** [comment]
Arianne scheduled a session for July 13th.

**Comment by josef-widder** [comment]
I guess it didn't happen after all. @milosevic , @ariannef , @ancazamfir : should we try to schedule it for some upcoming dev session? @konnov would really like to ;-)

**Comment by josef-widder** [comment]
just happened. great discussion.
