### ISSUE TITLE
Introduce tracebility tags for the English light client spec

### ISSUE THREAD

**Issue by konnov** [informalsystems/tendermint-rs#379]
Currently, [docs/spec/lightclient/verification.md](https://github.com/informalsystems/tendermint-rs/blob/master/docs/spec/lightclient/verification.md) is lacking tags. We need them to refer to from the TLA+ spec.

**Comment by ebuchman** [comment]
Maybe I'm missing something but looks like there's tons of tags. Some missing in a specific section?

**Comment by josef-widder** [comment]
> Maybe I'm missing something but looks like there's tons of tags. Some missing in a specific section?

There are some comments in the TLA+ spec where it says something like "add tags in English spec" for some formulas. I talked to Igor, while he wrote that issue, so the issue text is not so explicit. I know what to do and will take care of that.
