### ISSUE TITLE
Reduce/eliminate `light-client` dependency on `tendermint`crate

### ISSUE THREAD

**Issue by ebuchman** [informalsystems/tendermint-rs#387]
The previous version of the light client was virtually independent of the tendermint crate. It achieved this through aggressive use of traits. One of the main motivations of the refactor was to eliminate these traits because they made the library harder to use. However in doing so, the light client crate is now highly coupled to the tendermint crate, in that virtually all light client functionality requires concrete Tendermint data structure. This creates other difficulties, for instance in testing (https://github.com/informalsystems/tendermint-rs/issues/330#issuecomment-645868104), but also in testing uses of the light client eg. in IBC (#381).

We do still have some traits, eg. VotingPowerCalculator, but even those methods take concrete types, so it's not clear to me what the value is of them. It's thus very difficult to write unit tests for these components as they require large and complex object graphs. Our current plan seems to be to generate the complete types from JSON template, which could be useful and powerful regardless, but it still suggests the code could be improved.

I mentioned this somewhat in #294.

My original understanding of the refactor was that we would use simplified concrete types to represent Tendermint data instead of the actual types. Eg. a `light::Header` type that only had the ~5 fields we need, not the full ~15, and we would map the `tendermint::Header` to `light::Header` whenever we need it. I'm not sure exactly how we'd abstract over the validators and commits, but my understanding was that we would pass in closures that close over the complex-type-specific functionality. There's probably a lot more detail to figure out in exactly how this would work (it was even a bit tricky in the old version that just used traits to get this right, where eg. [validator set was an associated type for commit](https://github.com/informalsystems/tendermint-rs/blob/v0.13.0/tendermint/src/lite/types.rs#L46)), but it's probably worth doing, especially because we're expecting data types to change and we may want the light client functionality to work for say multiple versions of the Tendermint commit structure.

**Comment by brapse** [comment]
Refactored this into #416
