### ISSUE TITLE
RPC client incompatibility with Tendermint 0.32 /block_results endpoint

### ISSUE THREAD

**Issue by tarcieri** [informalsystems/tendermint-rs#4]
Copying/pasting this from https://github.com/tendermint/kms/issues/286 as reported by @devashishdxt

> In https://github.com/tendermint/tendermint/pull/3643, `tags` were changed to `events` (`event` now have an `event_type` and a list of `tags`). This change will affect RPC calls such as `/block_results` (https://github.com/tendermint/kms/blob/master/tendermint-rs/src/abci/responses.rs#L71).

**Comment by ebuchman** [comment]
@greg-szabo is this fixed for v0.33? Not sure we'll fix all this stuff for v0.32

**Comment by ebuchman** [comment]
ping @greg-szabo ?

**Comment by greg-szabo** [comment]
Hi, sorry I missed the notifications on this. Yes, this is fixed in 0.33.
