### ISSUE TITLE
light-client: remove preconditions in user-facing functions in favor of proper error handling

### ISSUE THREAD

**Issue by romac** [informalsystems/tendermint-rs#400]
Such preconditions should be only be used to assert internal invariants, and leave it to user-facing functions to do the appropriate checks and bail out with a proper error in case they don't hold.

cf. https://github.com/informalsystems/tendermint-rs/pull/394#discussion_r447714278

**Comment by ebuchman** [comment]
Was this done?

**Comment by romac** [comment]
The precondition of `LightClient::verify_to_target` was already commented out, as it is checked in the verification loop anyway. I am preparing a PR to remove it altogether.

Now, we also have preconditions on a bunch of "abstract methods", ie. methods in traits such as `Scheduler::schedule` and `EvidenceReporter::report`. We have to decide how we want to treat those, as the traits these methods are defined on are public and exported. On one hand it would be useful to keep those pre- and post-conditions, as they both document and enforce (albeit at runtime) the contract of the methods for downstream implementers. On the other hand, those are public types and methods and could thus cause panics at runtime should one not uphold the contracts.

I see three potential solutions there:

1. Keep these contracts, let downstream implementors deal with the runtime errors if they don't uphold the contracts.
2. Remove these contracts altogether, only keep them in textual form in the doc comment of the methods.
3. Refactor these traits by splitting the methods with contracts into two methods: a concrete one with the original name which performs the checks explicitly, returns a `Result` to propagate contracts not being upheld, and which delegates the actual computation to a fully abstract method:

```rust
#[contract_trait]
#[allow(missing_docs)] // This is required because of the `contracts` crate (TODO: open/link issue)
pub trait Scheduler: Send {
    /// Decides what block to verify next.
    ///
    /// ## Precondition
    /// - The light store contains at least one verified block. [LCV-SCHEDULE-PRE.1]
    ///
    /// ## Postcondition
    /// - The resulting height must be valid according to `valid_schedule`. [LCV-SCHEDULE-POST.1]
    #[pre(light_store.latest_trusted_or_verified().is_some())]
    #[post(valid_schedule(ret, target_height, current_height, light_store))]
    fn schedule(
        &self,
        light_store: &dyn LightStore,
        current_height: Height,
        target_height: Height,
    ) -> Height;
```

```rust
pub trait Scheduler: Send {
    /// Decides what block to verify next.
    ///
    /// This method should not be overriden, but rather the [`schedule_impl`]() method of this trait.
    ///
    /// ## Assumed Precondition
    /// - The light store contains at least one verified block. [LCV-SCHEDULE-PRE.1]
    ///
    /// ## Required Postcondition
    /// - The resulting height must be valid according to `valid_schedule`. [LCV-SCHEDULE-POST.1]
    fn schedule(
        &self,
        light_store: &dyn LightStore,
        current_height: Height,
        target_height: Height,
    ) -> Result<Height, Error> {
        if !light_store.latest_trusted_or_verified.is_some() {
            return ErrorKind::NoLatestTrustedOrVerifiedBlock.into();
        }

        let result = self.schedule_impl(light_store, current_height, target_height);

        if !valid_schedule(result, target_height, current_height, light_store) {
            return ErrorKind::InvalidScheduledHeight(result).into();
        }

        Ok(result)
    }

    /// Decides what block to verify next.
    ///
    /// ## Soft Precondition
    /// - The light store contains at least one verified block. [LCV-SCHEDULE-PRE.1]
    ///
    /// ## Soft Postcondition
    /// - The resulting height must be valid according to `valid_schedule`. [LCV-SCHEDULE-POST.1]
    fn schedule_impl(
        &self,
        light_store: &dyn LightStore,
        current_height: Height,
        target_height: Height,
    ) -> Height;
}
```

4. Refactor these methods into a trait with fully abstract methods and concrete functions which take an instance of the trait and enforce the contracts:

```rust
trait Scheduler {
    fn schedule(
        &self,
        light_store: &dyn LightStore,
        current_height: Height,
        target_height: Height,
    ) -> Height;
}

fn schedule(
   schedule: impl Scheduler,
    light_store: &dyn LightStore,
    current_height: Height,
    target_height: Height,
) -> Result<Height, Error> {
    if !light_store.latest_trusted_or_verified.is_some() {
        return ErrorKind::NoLatestTrustedOrVerifiedBlock.into();
    }

    let result = scheduler.schedule(light_store, current_height, target_height);

    if !valid_schedule(result, target_height, current_height, light_store) {
        return ErrorKind::InvalidScheduledHeight(result).into();
    }

    Ok(result)
}
```

---

If we do not expect downstream users to use the `Scheduler` or `EvidenceReporter` traits and instances directly, then I would be partial to option 1. I would imagine that most users of the crate will only interact with the light client via the `Supervisor` and `Handle` interface, and will not schedule or report light blocks themselves so that seems like the most lightweight correctness-preserving solution to me.

Let me know what you think!

**Comment by ebuchman** [comment]
Thanks for the detailed write up. Interesting to have 3 and 4 in mind for future reference but probably for now we should air on the side of sticking with 1 and just document this clearly. In general we should be trying to minimize public APIs for downstream users especially while things are still in flux - even if they have to be public in the workspace for other crates we should distinguish from whats actually expected to be used by downstream users. Not sure the cleanest way to do that, but otherwise sounds like we can close this. If there is a way to distinguish public-for-downstream-users and public-for-workspace maybe we open a new issue for that?

**Comment by romac** [comment]
>  If there is a way to distinguish public-for-downstream-users and public-for-workspace maybe we open a new issue for that?

There is no not, afaik. [This RFC](https://github.com/rust-lang/rfcs/pull/2315) proposed that `pub(crate)` would extend to the whole workspace but it's unfortunately been rejected/postponed.
