### ISSUE TITLE
Fail on Clippy errors in CI

### ISSUE THREAD

**Issue by romac** [informalsystems/tendermint-rs#406]
Once as [`clippy_check`](https://github.com/informalsystems/tendermint-rs/runs/829965075), as configured in `.github/workflows/rust.yml`, with a JSON output that's not very helpful.

Another time as [`clippy`](https://github.com/informalsystems/tendermint-rs/runs/829975639) which produces useful annotations. I am not sure where this one comes from.

I suggest removing the `clippy_check` job, and while we are at it, turn `clippy` warnings into CI failures (not sure how to do this, since I don't know where this job is actually set up).

**Comment by liamsi** [comment]
> Another time as clippy which produces useful annotations. I am not sure where this one comes from.

I think the 2nd one is just the output of the first (the `clippy_check` action). But I agree that it would be nice to fail on clippy instead of. Can easily be done by directly calling clippy instead of using the `clippy_check` action which creates these annotations).

**Comment by xla** [comment]
Related to #193
