### ISSUE TITLE
Light client might downgrade already `Trusted` blocks to `Verified`

### ISSUE THREAD

**Issue by romac** [informalsystems/tendermint-rs#418]
In the light client verification loop, we only look in the store for a block at the current height that is either `Verified` or `Unverified` (ie. we fetch it from a node), which may miss a block that has previously gone through fork detection and has been marked as `Trusted`. We then fetch it again from the peer, go through verification again, and then override its status to `Verified`, thus downgrading it from `Trusted` to `Verified`.

This is an issue because:

a) it's wasteful to re-fetch and re-verify a block from a node when we already trust it.
b) we may end up downgrading the status of a trusted block to verified, whether or not we fix a)

So I guess the question here is: what do we do if, during bisection, we encounter a block to verify that has i) already been verified, or ii) is already trusted?

Do we skip verification altogether and just move on to (schedule) the next block to verify?
Do we reverify the block anyway, and ensure we don't downgrade it's status if verification succeeds?
Something else?

---

- https://github.com/informalsystems/tendermint-rs/blob/142796b0cc37319f91af55cf2703b96a0cb80230/light-client/src/light_client.rs#L157
- https://github.com/informalsystems/tendermint-rs/blob/142796b0cc37319f91af55cf2703b96a0cb80230/light-client/src/light_client.rs#L246

**Comment by romac** [comment]
I guess the question here is: what do we do if, during bisection, we encounter a block to verify that has a) already been verified, or b) is already trusted?

**Comment by romac** [comment]
Note: just updated the issue

**Comment by romac** [comment]
$ ping @OStevan @josef-widder @milosevic @ebuchman

**Comment by josef-widder** [comment]
There are several questions in the issue. First, in the last version of the spec, I considered trusted to be a special case of verified (e.g., latestverified may also return a trusted header).

Second, in the current spec, I thought that such a case does not exists (revisiting a verified lightblock in the loop). If a height < latestverified should be verified, we generate an auxiliary lightstore that only contains one (older) header. I think we should discuss how such cases you mention can show up?

**Comment by romac** [comment]
> There are several questions in the issue. First, in the last version of the spec, I considered trusted to be a special case of verified (e.g., latestverified may also return a trusted header).

Right, that's something I've fixed as part of #419.

> Second, in the current spec, I thought that such a case does not exists (revisiting a verified lightblock in the loop). If a height < latestverified should be verified, we generate an auxiliary lightstore that only contains one (older) header. I think we should discuss how such cases you mention can show up?

True, I overlooked that `height < latest_verified` is the only case where that could happen, but that's not handled yet in the code. So I guess it's currently a non-issue, and won't ever happen either once we handle that case.

Closing this and re-opening an issue for the first item.
