### ISSUE TITLE
light-node: followups

### ISSUE THREAD

**Issue by liamsi** [informalsystems/tendermint-rs#442]
# Description 

#430 puts together a _light-node_ and surfaced a few things regarding the light-client crate as well as a room for further improvement in the light-node itself.

I tried to order them in terms of priorities.

## Subjective initialization
Existing related issue: https://github.com/informalsystems/tendermint-rs/issues/293#issue-629635994
It is critical that we do subjective initialzation correctly:

- It seems like it is underspecified how subjective intialization is supposed to work in detail. In particular in the light of having multiple peers (fork-detection): 
  -  https://github.com/informalsystems/tendermint-rs/pull/430#discussion_r452789386
  - https://github.com/informalsystems/tendermint-rs/pull/430/files#r453651166

Additionally, the light-client crate should provide a simple way to subjectively init (instead of doing this in the calling code, here the light-node crate):
 - https://github.com/informalsystems/tendermint-rs/pull/430#discussion_r452791199
 - https://github.com/informalsystems/tendermint-rs/pull/430/files#r452658506
 - https://github.com/informalsystems/tendermint-rs/pull/430#discussion_r452802711

## light-node

Cargo.toml:

 - ~~add meta data: https://doc.rust-lang.org/cargo/reference/publishing.html#before-publishing-a-new-crate~~ (done)
 - ~~allow publishing: https://github.com/informalsystems/tendermint-rs/blob/aefb3e062bb9026d765db509a676a9492b3c23f2/light-node/Cargo.toml#L6~~ (done and published)

Testing:
 - write and run acceptance tests against a docker image: https://github.com/informalsystems/tendermint-rs/pull/430#discussion_r453023040

Config & CLI arguments:
 - make the interval the light client tries to sync configurable: https://github.com/informalsystems/tendermint-rs/pull/430/files#r452662679
 - consider distinction between primary/witness in config: https://github.com/informalsystems/tendermint-rs/pull/430/files#r453551048
- consider naming options for init (height & hash): https://github.com/informalsystems/tendermint-rs/pull/430#discussion_r453543725

Error handling / exiting:
 - consider `process::exit`alternatives: https://github.com/informalsystems/tendermint-rs/pull/430/files#r452658991

## light-client
 - improve light store: https://github.com/informalsystems/tendermint-rs/pull/430#discussion_r452740214 and https://github.com/informalsystems/tendermint-rs/issues/428

**Comment by liamsi** [comment]
Everyone: feel free to grab and and work on any of the above issues. Best open a separate issue, assign that to yourself link it here. The subjective init discussions should happen in close coordination with the spec and research work!

**Comment by liamsi** [comment]
> write and run acceptance tests against a docker image: #430 (comment)

was split out into: https://github.com/informalsystems/tendermint-rs/issues/445

**Comment by milosevic** [comment]
Just heads up that I will work with Josef on clarifying initialisation spec. We will probably create a small PR in the following days.

**Comment by ebuchman** [comment]
Great work with the light node, just took it for a spin. I believe all the above is covered in existing or new breakout issues and we can close this.
