### ISSUE TITLE
light-node: acceptance test

### ISSUE THREAD

**Issue by brapse** [informalsystems/tendermint-rs#445]
### Context
Thanks to  #431 we have an integration test which tests the light-client initializations against a real (kv-store) tendermint application. This is great as the provides test coverage to the interface high level interfaces we expose for using our light client as a library. However with the landing of #430 we also expose an initialization process of the light client from the CLI via the light-node binary. 

### Problem
It would be good to have test coverage of the light-node initialization process and ensure there isn't too much duplication between library and binary usages.

Ref. #373

**Comment by ebuchman** [comment]
This should not just initialize but also run the light-node in CI and test the rpc endpoints. Will require setting up two tendermint full nodes to talk to since the light node only works with a witness ...

**Comment by greg-szabo** [comment]
Note from Ismail:
I think how tony did this could serve as an example (?) https://github.com/iqlusioninc/tmkms/blob/develop/tests/integration.rs
An alternative could be to write some scripts.

**Comment by tarcieri** [comment]
Note that there's some acceptance testing support built into Abscissa, although it's a bit rough around the edges:

https://docs.rs/abscissa_core/0.5.2/abscissa_core/testing/index.html

**Comment by thanethomson** [comment]
We've archived the light node as per #879
