### ISSUE TITLE
spec: proof of fork

### ISSUE THREAD

**Issue by ebuchman** [informalsystems/tendermint-rs#461]
Draft of the problem with more of an IBC lens is [here](https://github.com/informalsystems/tendermint-rs/blob/master/docs/spec/lightclient/detection/req-ibc-detection.md).

Primary next step is to flesh out the "proof of fork" data structures and protocol for light clients to submit to full nodes and to on-chain handlers. 

See the [next steps](https://github.com/informalsystems/tendermint-rs/blob/master/docs/spec/lightclient/detection/req-ibc-detection.md#next-steps) in the doc and further discussion in the [first PR reviews](https://github.com/informalsystems/tendermint-rs/pull/424)

**Comment by ebuchman** [comment]
As far as relationship between this follow up and the Go code:

1) "proof of fork" for on-chain clients - may require breaking changes to ICS07
2) "proof of fork" for full nodes - non-breaking changes to Tendermint Core
3) "evidence of misbehaviour" - breaking changes to Tendermint Core

Thus we should prioritize (1) and (3) as these may be breaking on IBC and Tendermint respectively, while (2) would be less disruptive changes to the RPC. That said, of course figuring out (2) may impact (3), so they need to be somewhat thought of together.

Since these changes are to a generally underused component of the system (evidence handling), these changes should not block other integrations against Stargate releases, but they may require testnet restarts.

**Comment by ebuchman** [comment]
@milosevic @josef-widder should we close this?

**Comment by josef-widder** [comment]
Yes. The on-chain accountability protocol is the next thing we are doing, but there are other issues for that.
