### ISSUE TITLE
Bug in predicate - is_within_trust_period 

### ISSUE THREAD

**Issue by Shivani912** [informalsystems/tendermint-rs#473]
**Context:** `is_within_trust_period` predicate is intended to check if the latest `trusted` header is still within trusting period while we verify a new, untrusted header. 

We also need to perform another check for header time that it's "header from future", that means, the `untrusted` header that we're verifying must not have a time that is beyond our current time (= now + clock_drift)

**Problem:** Code below for the `is_within_trust_period` predicate includes the "header from future" check.

This is a bug because the header we have there is the `trusted` one instead of the `untrusted` one and so the condition will always evaluate to `true`.

https://github.com/informalsystems/tendermint-rs/blob/548d76d8b7025f1a3ad1ee9adf32a5e6d24e2197/light-client/src/predicates.rs#L99-L121

**Fix:** Will be clearer if we have a separate predicate for "header from future" check.

**Comment by Shivani912** [comment]
Should I submit a PR for this?

**Comment by romac** [comment]
Yes please! Great catch
