### ISSUE TITLE
light-node: Initialization Follow up

### ISSUE THREAD

**Issue by ebuchman** [informalsystems/tendermint-rs#484]
Original issue https://github.com/informalsystems/tendermint-rs/issues/293#issue-629635994 was closed with #430. This is a breakout issue from #442.

Two main pieces:

- [ ] Specification needs to be clarified. Subjective init is currently under specified and this needs to be fixed. Eg. we may need to check that the initial trusted block is corroborated by witnesses (https://github.com/informalsystems/tendermint-rs/pull/430#discussion_r452789386)
- [x] `light-client` crate needs to expose functions for initialization. Currently the caller has to do some IO and set things up itself (https://github.com/informalsystems/tendermint-rs/pull/430#discussion_r452791199)

**Comment by brapse** [comment]
This is related to some specification work https://github.com/tendermint/spec/issues/131.

**Comment by ebuchman** [comment]
Per #422, consider using the [builder pattern](https://www.ameyalokare.com/rust/2017/11/02/rust-builder-pattern.html) to streamline creation of the light client instance

**Comment by ebuchman** [comment]
hey @romac, does #583 sufficiently address the second bullet point in this issue? 

@milosevic do we need to do anything more re the spec for initialization?

**Comment by romac** [comment]
> hey @romac, does #583 sufficiently address the second bullet point in this issue?

Yeah it does (even though we could still improve the API further)

**Comment by thanethomson** [comment]
Since the second point is marked as done and the specs have moved to https://github.com/tendermint/spec, I'm going to close this. Feel free to reopen if there's anything still needed for this issue that's relevant to this repo.
