### ISSUE TITLE
Light Node Config and CLI Followups

### ISSUE THREAD

**Issue by ebuchman** [informalsystems/tendermint-rs#485]
Breakout from https://github.com/informalsystems/tendermint-rs/issues/442:

 - [ ] make the interval the light client tries to sync configurable: https://github.com/informalsystems/tendermint-rs/pull/430/files#r452662679
 - [ ] consider distinction between primary/witness in config: https://github.com/informalsystems/tendermint-rs/pull/430/files#r453551048
- [ ] consider naming options for init (height & hash): https://github.com/informalsystems/tendermint-rs/pull/430#discussion_r453543725

Some more follow up:

- [ ] times should be strings like "5s" or "3w" or something more human readable than the current `secs` and `nanos` fields
- [ ] peer config should not require `peer_id` and `db_path` - we might as well just use the `address` to identify the peer since we don't authenticate the `peer_id` (though if we ever adopt a p2p reactor for the light client this would change). Then really all we need in the config is a list of tcp addresses ... but this might be a larger discussion about updating the PeerID in the `light-client` crate ...
- [ ] On startup it should log what block it's at before it starts syncing

**Comment by thanethomson** [comment]
Given that we archived the light node last year, I'm closing this for now. If there's anything from here that needs implementation in the light client itself, please let me know and we can reopen or open separate issues.
