### ISSUE TITLE
light-node: Error Handling and Exiting

### ISSUE THREAD

**Issue by ebuchman** [informalsystems/tendermint-rs#486]
Breakout issue from #442. 

- [ ] consider `process::exit` alternatives: https://github.com/informalsystems/tendermint-rs/pull/430/files#r452658991
- [ ] include peer address in error logs. ie. `error: sync failed: I/O error: Internal error: height 194 must be less than or equal to the current blockchain height 0 (code: -32603)` doesn't tell me what peer this issue is with.

**Comment by ebuchman** [comment]
@romac which part did #583 address ?

**Comment by thanethomson** [comment]
Light node was archived.
