### ISSUE TITLE
light-node: does not recover from primary restart

### ISSUE THREAD

**Issue by ebuchman** [informalsystems/tendermint-rs#487]
If I kill a witness process and then restart it, the light node will log some errors but recover gracefully. However if I kill the primary, the light client logs an error for ever and never recovers:

```
started RPC server: 127.0.0.1:8888
synced to block: 2391
synced to block: 2394
synced to block: 2397
error: sync failed: I/O error: error trying to connect: tcp connect error: Connection refused (os error 61) (code: 0)
error: sync failed: I/O error: error trying to connect: tcp connect error: Connection refused (os error 61) (code: 0)
synced to block: 2407
synced to block: 2410
synced to block: 2413
synced to block: 2416
synced to block: 2419
synced to block: 2423
synced to block: 2426
synced to block: 2429
error: sync failed: no witness left: no initial trusted state
error: sync failed: no witness left: no initial trusted state
error: sync failed: no witness left: no initial trusted state
error: sync failed: no witness left: no initial trusted state
```

Not sure how this would behave with three nodes but I'd think if the primary dropped and there were still two witnesses we'd be fine.

But since we can recover from a witness going down and coming back I'd think we could recover from the primary doing the same?

And if we're not going to recover here, probably better to exit than to keep throwing the error

**Comment by thanethomson** [comment]
Light node has now been removed/archived.
