### ISSUE TITLE
light-node: improve getting started

### ISSUE THREAD

**Issue by ebuchman** [informalsystems/tendermint-rs#488]
Getting started guide for the light node is great but a few possible improvements:

- [ ] `light_node.toml.example` is confusing because both peers use the same address. Should use different addresses for them
- [ ] leverage https://github.com/informalsystems/tendermint-rs/issues/445 to simplify setup for testing so folks can easily get a local set of full nodes to connect their light client to
- [ ] `curl -X GET "http://localhost:26657/block?height=2" -H  "accept: application/json"` can just be `curl localhost:26657/block?height=2`

**Comment by thanethomson** [comment]
We've archived the light node as per #879
