### ISSUE TITLE
upgrade sled to 0.34.1

### ISSUE THREAD

**Issue by tomtau** [informalsystems/tendermint-rs#490]
https://github.com/spacejam/sled/blob/master/CHANGELOG.md#0341

**Comment by thanethomson** [comment]
How does this affect the Light Client's operations?

Also, how do we manually test whether upgrading breaks the store? (Since we don't have capacity to write automated tests for this upgrade just yet).

**Comment by tomtau** [comment]
> How does this affect the Light Client's operations?

In 0.34.2: "transactions and writebatch performance has been significantly improved by removing a bottleneck in the atomic batch stability tracking code."

> Also, how do we manually test whether upgrading breaks the store? (Since we don't have capacity to write automated tests for this upgrade just yet).

maybe having a test script that will produce a binary blob with 0.33 / old binary release and try to read it with the upgraded version, asserting it contains all expected values?
