### ISSUE TITLE
When checking signatures, vote type is fixed to Precommit, irrespective of the actual type

### ISSUE THREAD

**Issue by andrey-kuprianov** [informalsystems/tendermint-rs#491]
I've encountered  this problem while executing my model-based tests. In the [`testgen`](https://github.com/informalsystems/tendermint-rs/tree/master/testgen), the default for a vote is `Prevote` (should it be `Precommit` actually?), while when calculating the signatures in [`lite_impl/signed_header.rs::voting_power_in()`](https://github.com/informalsystems/tendermint-rs/blob/667fc8d8be4ac1745b0ecb2284e14f7d87f4b2f0/tendermint/src/lite_impl/signed_header.rs#L17), more specifically [here](https://github.com/informalsystems/tendermint-rs/blob/667fc8d8be4ac1745b0ecb2284e14f7d87f4b2f0/tendermint/src/lite_impl/signed_header.rs#L126), the vote type is fixed to be `Precommit`, that's why the validation is failing.

Here are the two alternatives that I currently see, and both mean that it's probably a bug:
* If only `Precommit` votes are allowed in a `Commit`, then the `Prevote` votes included there should probably be ignored, but the rest of the votes still counted
* If both types of votes are allowed, then the vote type should be copied 'as is' when verifying signatures.

Could someone please clarify the issue?

**Comment by andrey-kuprianov** [comment]
or is it actually, that only `Precommit` votes can be used for making a commit? Because the `CommitSig` itself doesn't carry any vote type... Then there is no bug of course, and I should change the default vote type in `testgen` to `Precommit`.

**Comment by ebuchman** [comment]
Only Precommits can be included in a Commit. If a commit contains a signature from a Prevote it would be treated as invalid.

**Comment by andrey-kuprianov** [comment]
Ok, it's clear; thanks!
