### ISSUE TITLE
Remove DuplicateVoteEvidence PublicKey

### ISSUE THREAD

**Issue by greg-szabo** [informalsystems/tendermint-rs#502]
I just noted that in the go versions there is no pubkey field (anymore?). We need to remove this for compatibility. Tracking here: https://github.com/informalsystems/tendermint-rs/issues/300

_Originally posted by @liamsi in https://github.com/informalsystems/tendermint-rs/pull/242_

**Comment by marbar3778** [comment]
Not sure the path that has been taken in the repo, but it may be best to fetch the proto files and use those to generate your evidence types.

**Comment by greg-szabo** [comment]
Cool, thanks for the note. I'll visit this issue when I have the protos compiled into Rust.
