### ISSUE TITLE
Resistance to sybil attacks

### ISSUE THREAD

**Issue by leo-lb** [informalsystems/tendermint-rs#511]
Hello!

How does Tendermint handle sybils? Can Tendermint consensus be undermined by a flood in new identities in the system that all represent the same entity (sybil attack)?
If not, what exactly in Tendermint prevents this from happening and how does it work?

Thank you

**Comment by ebuchman** [comment]
This question can be asked at many levels, so we'd need you to be more specific about the kind of sybil attack you're talking about and what you mean by undermined. Tendermint consensus itself is "safe" so long as <1/3 of the validators are malicious but if the network is extremely unreliable (eg. from a DoS attack) it could be slowed down or in the worst case halted for some time ... In any case, these github issues are probably not the right place for it, so you could try the https://forum.cosmos.network for instance. 

Tendermint consensus itself uses public keys for validators, so only a specific set of predetermined (but dynamic) validators can sign votes. The p2p network does allow peers to come and go, so in principle someone could launch tons of peers, but at worst it should just slow the network down. P2P related stuff is continuously and progressively hardened. Anyways it's always possible for validators to establish private connections to each other to mitigate these kinds of Denial of Service attacks and ensure some level of connectivity.
