### ISSUE TITLE
light-node: run against a Tendermint image fails with clock drift

### ISSUE THREAD

**Issue by romac** [informalsystems/tendermint-rs#512]
After spawning a light node in a Docker container with:

```bash
$ docker run \
    -p 26656:26656 \
    -p 26657:26657 \
    -p 26660:26660 \
    tendermint/tendermint:v0.33.6
```

If we fetch the latest block height, hash and time via RPC, we get:

```bash
$ curl -X GET "http://localhost:26657/status" -H  "accept: application/json" | jq '.result.sync_info | {latest_block_hash,latest_block_height,latest_block_time}'
```
```json
{
  "latest_block_hash": "CCFF1A6907DB9DC08E7C58D9C590088D1522069FFDFF7ABD3E6D62DCD083DBC4",
  "latest_block_height": "2469",
  "latest_block_time": "2020-08-11T10:30:13.352595649Z"
}
```

Here we see that the block was committed at 10:30 UTC, whereas **both on my machine and within the Docker container**, the time is reported as 10:20 UTC, meaning that the block has been committed 10 minutes "in the future".

So if we initialize the light-node with the block above, by running:

```bash
$ cargo run -- initialize 2469 CCFF1A6907DB9DC08E7C58D9C590088D1522069FFDFF7ABD3E6D62DCD083DBC4
```

and then start the light node with:

```bash
$ cargo run -- start
```

we get:

```
started RPC server: 127.0.0.1:8888
error: sync failed: no witness left: no initial trusted state
error: sync failed: no witness left: no initial trusted state

etc.
```

After sprinkling some `dbg!` statements in the supervisor, we indeed see that verification fails because the headers pulled from the node are "from the future":

```
[light-client/src/supervisor.rs:221] &verdict = Err(
    Error(
        Context {
            kind: InvalidLightBlock(
                HeaderFromTheFuture {
                    header_time: Time(
                        2020-08-11T10:32:44.352595649Z,
                    ),
                    now: Time(
                        2020-08-11T10:22:58.589649Z,
                    ),
                },
            ),
```

Again, a 10 minutes clock drift.

What is weird here, is that the reported time on both my machine and within the Docker container actually do match, which may point to a configuration issue in the Docker image.

The very same behavior has been observed by @brapse on his machine.

---

If we do the same operations above against a full node started with `tendermint node --proxyapp=kvstore`, things work out just fine and the light node continuously syncs to the latest block without issues:

```
started RPC server: 127.0.0.1:8888
synced to block: 5006
synced to block: 5007
synced to block: 5008

etc.
```

**Comment by liamsi** [comment]
potentially related: https://github.com/tendermint/tendermint/pull/5087
also note: the above changes led to an updated docker image, can you confirm that the same happens with `0.33.6-1` (not `0.33.6`)?

![image](https://user-images.githubusercontent.com/7441766/89894767-f2bc4680-dbda-11ea-926e-f363dd4aaa1f.png)

**Comment by romac** [comment]
I am getting the following error when trying to run the `v0.33.6-1` image:

```
$ docker run \
    -p 26656:26656 \
    -p 26657:26657 \
    -p 26660:26660 \
    tendermint/tendermint:v0.33.6-1
Unable to find image 'tendermint/tendermint:v0.33.6-1' locally
v0.33.6-1: Pulling from tendermint/tendermint
31603596830f: Already exists
4a2577fcf4b4: Pull complete
5f336b89e9bb: Pull complete
2aaaed0f8a43: Pull complete
Digest: sha256:4379e773819489b68d37075ab7913d9e1e98ac622ed9c6b184ba63d2e0a2b42e
Status: Downloaded newer image for tendermint/tendermint:v0.33.6-1
docker: Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"docker-entrypoint.sh\": executable file not found in $PATH": unknown.

$ docker run \
    -p 26656:26656 \
    -p 26657:26657 \
    -p 26660:26660 \
    tendermint/tendermint:v0.33.6-1

docker: Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"docker-entrypoint.sh\": executable file not found in $PATH": unknown.
```

**Comment by romac** [comment]
Looks like there are other issues with this image:

```
docker run \
    -p 26656:26656 \
    -p 26657:26657 \
    -p 26660:26660 \
    --entrypoint bash \
    -it \
    tendermint/tendermint:v0.33.6-1

bash-4.4$ /usr/bin/tendermint node --proxy_app=kvstore
bash: /usr/bin/tendermint: cannot execute binary file: Exec format error
```

**Comment by romac** [comment]
The image at version `v0.33.7` does not exhibit the same issue as `v0.33.6-1` but its clock still seems to drift more and more.

To me it looks like the clock that the Tendermint node sees runs faster than my own, and ends up drifting further away faster and faster. On the other hand, the clock of the container itself (queried via the `date` command) seems to match my own perfectly.

I can reproduce this by setting the `clock_drift` param to 10 seconds, running the light node, and seeing it successfully syncs to the latest blocks for a while and then suddenly failing with an error about the header being from the future.

**Comment by liamsi** [comment]
> docker: Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"docker-entrypoint.sh\": executable file not found in $PATH": unknown.

Meh, I'll look into that.

**Comment by liamsi** [comment]
opened: https://github.com/tendermint/tendermint/issues/5230

**Comment by liamsi** [comment]
> To me it looks like the clock that the Tendermint node sees runs faster than my own, and ends up drifting further away faster and faster. On the other hand, the clock of the container itself (queried via the date command) seems to match my own perfectly.

I can confirm this really confusing behaviour :-/ 
```
[light-client/src/supervisor.rs:256] &err = Error(
    Context {
        kind: InvalidLightBlock(
            HeaderFromTheFuture {
                header_time: Time(
                    2020-08-11T17:35:44.799217211Z,
                ),
                now: Time(
                    2020-08-11T17:33:57.667060Z,
                ),
            },
        ),
```
If I wait a few minutes and start again, I e.g. get:
```
[light-client/src/supervisor.rs:256] &err = Error(
    Context {
        kind: InvalidLightBlock(
            HeaderFromTheFuture {
                header_time: Time(
                    2020-08-11T17:48:07.159481311Z,
                ),
                now: Time(
                    2020-08-11T17:42:04.000055Z,
                ),
            },
        ),
```

And the diff gets larger by time... As Romac already noted.

Last time, I played around with this, this didn't happen. We did add in a change regarding time right?

**Comment by andynog** [comment]
not that this might matter but interesting to see that the time values differ in the precision just wondering if somewhere in the code there's different implementations to grab the time or something like this. Just an observation, didn't do any investigation.

**Comment by romac** [comment]
In the error above, the `header_time` is parsed from the JSON returned over RPC by the Go implementation, while `now` is queried via the [`chrono`](https://docs.rs/chrono) crate, which may explain the difference in precision. I don't think that this really matters, as the times reported by

a) `chrono` on my machine
b) `$ date` on my machine
c) `$ date` within the container

all agree with each other. It seems to only be the time that the Tendermint node sees that is drifting.

**Comment by liamsi** [comment]
Can you confirm that behaviour is not related to docker, i.e. does it also occur when running the node locally too?

**Comment by romac** [comment]
> @liamsi Can you confirm that behaviour is not related to docker, i.e. does it also occur when running the node locally too?

Perhaps fortunately, I am unable to reproduce the clock drift when running the light node against a local Tendermint node (using the binary from the v0.33.6 release, `0.33.6-606d0a89`).

So it seems that this is an issue with Docker, and perhaps only on Mac? I don't have a Windows or Linux machine/VM at hand at the moment, so I am unable to check whether the issue also appears on these platforms.

**Comment by xla** [comment]
How would we like to continue with this? It seems it's specific to a single container version. I'd be in favor of closing the issue and revisit if this behavior pops up again.

**Comment by romac** [comment]
It's not specific to a single version, I get the same behavior with v0.33.6-1 and v0.33.7.

**Comment by liamsi** [comment]
@marbar3778 brought this to my attention: https://github.com/tendermint/tendermint/issues/4489
It looks related but needs further investigation.

**Comment by ebuchman** [comment]
Wow seems like a known docker issue? https://www.docker.com/blog/addressing-time-drift-in-docker-desktop-for-mac/

Not sure exactly what the state of solutions is there or if this is the same issue but seems we might be able to find a solution by googling around a little bit ? Or upgrading docker for mac?

**Comment by romac** [comment]
Yeah I saw this blog post while investigating (forgot to link it here, sorry for having you redo the googling…). They seem to say that they've somehow fixed it in recent versions of Docker for Mac, which I was running, to no avail. Also, this post talks about drift in the order of 20ms per 30s, whereas we are seeing exponential drift, up to a few seconds of clock drift but second of wall time.

Now that I am re-reading the blog post, I am thinking we could perhaps try to implement ourselves one of the solution they dismissed, ie. continuously forcing synchronization with the hardware clock by periodically running `hwclock -s` in the background.

I am not quite sure what they mean by:

> Unfortunately running `hwclock -s` in a HyperKit Linux VM only manages to keep the clock in sync within about 1s, which would be quite noticeable when editing code and immediately recompiling it. So we’ll stick with NTP.

Is it that the sync takes up to 1s or that the clock drift may still amount to up to 1s?

Did a quick test in the tendermint image, but running `hwclock` fails with:

> hwclock: can't open '/dev/misc/rtc': No such file or directory

**Comment by romac** [comment]
Actually, now that I am re-reading this thread, and specifically [this comment](https://github.com/informalsystems/tendermint-rs/issues/512#issuecomment-672794426):

> In the error above, the header_time is parsed from the JSON returned over RPC by the Go implementation, while now is queried via the chrono crate, which may explain the difference in precision. I don't think that this really matters, as the times reported by
> 
> a) chrono on my machine
> b) $ date on my machine
> c) $ date within the container
> 
> all agree with each other. It's only the time seen by the Tendermint node that is drifting.

Everything points to this being an issue with Tendermint Go.

**Comment by romac** [comment]
Looks like this has been fixed in Tendermint Go: https://github.com/tendermint/tendermint/issues/4489#issuecomment-696863504
