### ISSUE TITLE
light-client: factor out test functions from integration tests

### ISSUE THREAD

**Issue by andrey-kuprianov** [informalsystems/tendermint-rs#524]
Current tests in the `light-client` crate, in the integration tests [light_client.rs](https://github.com/informalsystems/tendermint-rs/blob/master/light-client/tests/light_client.rs), [supervisor.rs](https://github.com/informalsystems/tendermint-rs/blob/master/light-client/tests/supervisor.rs) contains a lot of duplicate code for reading tests files, iterating over directories with tests, etc. This code can be factored out into commonly usable functions, which is probably useful also for other crates. 

Another advantage of such a refactoring is that it will fit better with the test files organization, and will be able to provide better overview of the successful/failing tests.

In the near future this will provide also the basis for automating running of the model-based tests, and their integration with the CI (see #414 )

**Comment by ebuchman** [comment]
Believe this was done in #525?
