### ISSUE TITLE
Consolidate, deduplicate, reorganize remaining amino_types

### ISSUE THREAD

**Issue by greg-szabo** [informalsystems/tendermint-rs#536]
After all amino encoding was changed to protobuf, rename the folder name (and all outstanding comments).

This is considered the last step because reviewing folder renames is cumbersome.

**Comment by ebuchman** [comment]
As discussed, we might be able to do away with this folder completely. Previous it held amino types which are now effectively our raw types in the proto crate. I think all that's left are Canonical types for signing and request/response types for the KMS, which should be moved into their own modules.  The rest of the types should be redundant with our domain types and should be consolidated with them.

**Comment by greg-szabo** [comment]
Additional note: with #571 we have the ability to get rid of the AminoMessage trait. Let's do that too in this issue.
