### ISSUE TITLE
merkle: temporarily revert #514

### ISSUE THREAD

**Issue by thanethomson** [informalsystems/tendermint-rs#538]
We need to temporarily revert #514 in order to cut the v0.16.0 release.

**Comment by greg-szabo** [comment]
This is the (squashed) commit that we're talking about: https://github.com/informalsystems/tendermint-rs/commit/92956766c3aa3973c274b52e1d458a1accc89bb4

It's made up of three commits that were squashed:
1. merkle.rs line 24, length == 0 match calls the new `empty_hash()` function
2. Test to see that it works
3. linting (I guess that can stay)
