### ISSUE TITLE
light-node: Re-enable test commented out because of cargo bug surfaced in WASM PR

### ISSUE THREAD

**Issue by romac** [informalsystems/tendermint-rs#560]
In the WASM PR (#553), I had to disable the only previously enabled acceptance test of the light node CLI for the test suite to pass (https://github.com/informalsystems/tendermint-rs/pull/553/commits/7c0713467c15143c4b517509277f9b7a2dcaae0b). 

Without this commit, `cargo test --all-features --no-fail-fast` would fail with:

```
       Doc-tests tendermint-light-client
    error[E0460]: found possibly newer version of crate `tendermint` which `tendermint_rpc` depends on
     --> /Users/coromac/Informal/Code/Current/tendermint-rs/light-client/src/components/io.rs:7:5
      |
    7 | use tendermint_rpc as rpc;
      |     ^^^^^^^^^^^^^^
      |
      = note: perhaps that crate needs to be recompiled?
      = note: the following crate versions were found:
              crate `tendermint`: /Users/coromac/Informal/Code/Current/tendermint-rs/target/debug/deps/libtendermint.rlib
              crate `tendermint`: /Users/coromac/Informal/Code/Current/tendermint-rs/target/debug/deps/libtendermint-735716e8d731096d.rmeta
              crate `tendermint_rpc`: /Users/coromac/Informal/Code/Current/tendermint-rs/target/debug/deps/libtendermint_rpc-ad41c355acf2752f.rlib

    error: aborting due to previous error
```

It is currently unclear why this error has appeared, though I suspect it is a bug in Cargo related to features flags (which we now use to disable non WASM-compatible code).

The likely reason for why disabling this test resolves the issue above, is that there is no more a need to rebuild the light node crate to run the light node binary with `cargo run`. It's not clear why rebuilding the crate is necessary when running `cargo run` as part of the test (when everything should have been compiled already, though perhaps not with the same flags) but I suspect that doing so in the middle of running (doc)tests is causing the issue.

**Comment by thanethomson** [comment]
Seems like this may no longer be relevant?
