### ISSUE TITLE
spec: move specs to tendermint/spec repo

### ISSUE THREAD

**Issue by josef-widder** [informalsystems/tendermint-rs#561]
We want to consolidate all spec work at the tendermint/spec repo so that it becomes a central access point for specs

**Comment by josef-widder** [comment]
All active work on specs is now happening at tendermint/spec. The plan was to delete the specs here, or more precisely, keep empty files with links to the new location (as we referenced the files in our recent publications). However, for the model-based testing, @andrey-kuprianov needs the TLA+ specs within the tendermint-rs repository. We should figure out how to proceed here.

**Comment by andrey-kuprianov** [comment]
In fact, for MBT I have copied and modified the spec files I need into the LightClient crate. It's safe to remove the old spec files now

**Comment by ebuchman** [comment]
Closing for https://github.com/informalsystems/tendermint-rs/issues/601
