### ISSUE TITLE
Fix tests for v0.34 upgrade

### ISSUE THREAD

**Issue by ebuchman** [informalsystems/tendermint-rs#567]
Various JSON based tests have been disabled as we've been upgrading to v0.34. See #563 and others (?).

We should regenerate these tests with the new testgen tooling and otherwise work towards better documentation of whats being tested and how. 

As part of this work we should do a diligent sweep of all the JSON structs and read through #197 again to make sure we got everything :)

**Comment by andrey-kuprianov** [comment]
I will assign this to @Shivani912, as we already discussed this task with her. But it will definitely happen for the 0.18 release, not 0.17 -- some tests can be reproduced using TLA+ assertions, some require fuzzing (#564); namely those with `wrong_` and `faulty_` prefixes.

I propose that we keep the disabled tests as is for 0.17 release, and fix them for 0.18. We could also do a patch release of course, but it will definitely require smth around 2 weeks to finish.

**Comment by greg-szabo** [comment]
Andrey and Shivani already created and recreated a bunch of tests for us for the 0.17 release using `testgen`. Those tests gave me enough confidence that the changes in the release are working.

If we have additional tests that are disabled and need to be recreated, then those will go into the 0.18 or 0.17.1 release as mentioned above.

I'm moving this to 0.17.1 for now. We should at least review what's missing there and get a good grip of how much work it will take to fix it.

**Comment by romac** [comment]
May I ask where we are we on this?

I am asking because @cezarad was looking for a test case exercising the happy path of the light client bisection loop, but that testcase has been disabled in #563. On top that, I am also a bit wary of releasing v0.17 with that many missing testcases.

Let me know if I can be of any help with that :)
