### ISSUE TITLE
Testgen: validator signatures don't verify

### ISSUE THREAD

**Issue by Shivani912** [informalsystems/tendermint-rs#570]
Unit test for predicate `has_sufficient_validators_overlap` fails on signature verification and results into `InvalidSignature` error. I suspect it's related to how Testgen signs the vote, not sure though.

**Failing unit test:**
https://github.com/informalsystems/tendermint-rs/blob/1a3429ecc9c685a59008b4a39e6f21a8769cdbd5/light-client/src/predicates.rs#L757

FYI: If you run it locally, you'll see the test passing and the `InvalidSignature` error printed in terminal because
https://github.com/informalsystems/tendermint-rs/blob/1a3429ecc9c685a59008b4a39e6f21a8769cdbd5/light-client/src/predicates.rs#L776-L777

**Comment by andrey-kuprianov** [comment]
@Shivani912 I am not sure we can call this a "bug": it's not in the production code, only in the testing one. And testgen is not properly polished at all yet. To fix this issue someone just needs to do a debugging session and go over the code path, to see what's happening. If you could do it, would be great; otherwise I could probably help with it next week.

**Comment by Shivani912** [comment]
@andrey-kuprianov Yeah although it's not in production code, it plays an important role in making sure the production code is correct (as it's part of MBT too). So I considered this to be a bug in Testgen. I'm working on this, just wanted it to be in an issue so if anyone knows about, it'd help.

**Comment by andrey-kuprianov** [comment]
perfect, thanks for taking care of this:) I just wanted to say that I know for sure that Testgen is incomplete (e.g. many fields in the header are just assigned nulls). So, it's rather the process of making it more complete wrt. the Tendermint code, than of fixing bugs in it.

**Comment by Shivani912** [comment]
Oh yes, you're right about that :) @andrey-kuprianov

**Comment by Shivani912** [comment]
This is already fixed, so closing it now :)
