### ISSUE TITLE
light-client: Verification failure

### ISSUE THREAD

**Issue by thanethomson** [informalsystems/tendermint-rs#600]
Follows from [this comment in issue 583](https://github.com/informalsystems/tendermint-rs/pull/583#issuecomment-700894882). The issue is reproducible in the code currently on `master`, specifically [this integration test](https://github.com/informalsystems/tendermint-rs/blob/a1d51fa28eb18dcf8b5935dd6920fb29842c90f1/light-client/tests/integration.rs#L68).

To reproduce locally, in one terminal, run a Tendermint kvstore accessible at `tcp://127.0.0.1:26657`:

```bash
docker run -it --rm -v "/tmp/tendermint:/tendermint" tendermint/tendermint init
docker run -it --rm -v "/tmp/tendermint:/tendermint" -p 26657:26657 tendermint/tendermint node --proxy_app=kvstore
```

Then set [this variable](https://github.com/informalsystems/tendermint-rs/blob/a1d51fa28eb18dcf8b5935dd6920fb29842c90f1/light-client/tests/integration.rs#L108) to a value arbitrarily higher than 1 (e.g. 10).

Then, from the root of the repository:

```bash
cd light-client
cargo test --all-features sync -- --nocapture --ignored
```

The test fails with a result along the lines of:

```
running 1 test
[info ] - iteration 1/10
[info ] synced to block 219
[info ] - iteration 2/10
[error] sync failed: no witness left: invalid light block: invalid commit value: header_hash=1735EC2938A2377C3C0EB730C9DF28FA22EBEC88A6C01EB6201BBC377E636D23 commit_hash=142DBB6210610A1349163B6611A1338A00E186DE586783F3F16DD964604E812E
thread 'sync' panicked at 'failed to sync to highest: no witness left: invalid light block: invalid commit value: header_hash=1735EC2938A2377C3C0EB730C9DF28FA22EBEC88A6C01EB6201BBC377E636D23 commit_hash=142DBB6210610A1349163B6611A1338A00E186DE586783F3F16DD964604E812E', light-client/tests/integration.rs:111:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
test sync ... FAILED
```

**Comment by romac** [comment]
Will be fixed in #592 by https://github.com/informalsystems/tendermint-rs/pull/592/commits/007bb098d6b9eb155e984adea4b6a3f94819ebb5.
