### ISSUE TITLE
Testgen: Need a way to generate chain of LightBlocks

### ISSUE THREAD

**Issue by Shivani912** [informalsystems/tendermint-rs#608]
ibc-rs testing requires some way to generate a Chain to be able to mock out a Tendermint blockchain ([see this issue](https://github.com/informalsystems/ibc-rs/issues/158))

Hoping to get this asap!

**Comment by andrey-kuprianov** [comment]
closed via this PR: https://github.com/informalsystems/tendermint-rs/pull/606
