### ISSUE TITLE
testgen use more tendermint types

### ISSUE THREAD

**Issue by greg-szabo** [informalsystems/tendermint-rs#619]
On the conformance test call Greg was advocating for using more Tendermint types and implementing less new types so when any protobuf types change, the Testgen code doesn't blow up.

Research the idea of implementing a `struct ProtoHeader(Vec<Header>)` newtype where Proto stands for " indicating the first or earliest or original" and not protobuf. :) (Maybe with a different name...)

This issue is here to discuss advantages and disadvantages of implementing this.

**Comment by greg-szabo** [comment]
Although we didn't populate this issue, a few ideas and thoughts came up over the weeks. Essentially, testgen should consider Domain types as the black box to test and testgen has to be able to submit invalid structs for this testing. So using domain types in testgen is not very productive.

The idea of using the protobuf/json a.k.a. "raw" types for testgen came up: these types are well-defined and kept up-to-date, all fields are public, no constructors or restrictions on them and they mostly use primitive types. Also, all (most) of them have translators (TryFrom/Into) into domain types.

I'll leave that to Andrey and team, if they want to move to that path or keep updating testgen structs in parallel.

**Comment by andrey-kuprianov** [comment]
Thank you for your ideas, Greg! We will definitely investigate what you've raised up, as soon as we we go past the other pressing concerns.
