### ISSUE TITLE
rpc: expose server-related fields

### ISSUE THREAD

**Issue by CharlyCst** [informalsystems/tendermint-rs#625]
Hi,

If my understanding is correct, the RPC crate has been design with the goal of exposing types needed by clients to communicate with nodes, and thus hides server-related details.

This is reflected in multiple places, for instance in the endpoints where the fields of `Response` are public whereas those of `Request` are private.

However, I'm coming up with the opposite use case: I'm building a mocked node in order to test a client. With the current interface of the RPC crate I'm indeed able to deserialize incoming requests, but I can't access the fields to return a plausible response.

Would it be an option to expose server-related structs and fields to cover both client and server needs?

**Comment by adizere** [comment]
Hey, is it correct to say that these are the only changes necessary?

https://github.com/informalsystems/tendermint-rs/compare/master...CharlyCst:master

**Comment by CharlyCst** [comment]
Those are the only one I need at the moment in order to expose the interface I'm interested in, but ideally I would expect all the fields of all the `Request`s endpoint structs to be public, as it's the case for the `Response`s (see `rpc/src/endpoint/*` files).

**Comment by thanethomson** [comment]
No problem @CharlyCst! Thought I'd just implement it quickly. Mind taking a look at #636 and seeing if that'll meet your needs?

**Comment by CharlyCst** [comment]
Yes that's perfect, thank you!
