### ISSUE TITLE
Add From instance to Height for all unsigned integer types which fit in a i64

### ISSUE THREAD

**Issue by romac** [informalsystems/tendermint-rs#628]
In ibc-rs, especially in tests, we often constructs instances of `Height` where we statically know that the value will fit in a `i64`.
Currently, such code looks like this:

```rust
let height: Height = 0_64.try_into().unwrap(); // SAFETY: 0 <= i64::MAX
```

It would be nice if we could leverage the fact that some integer types [entirely fit](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=bdda71914fdeafa0cac1444baf1d1d58) in a `i64` (`u8`, `u16`, `u32`), such that if we had a `From` instance for all these types, we could rewrite the code above as:

```rust
let height: Height = 0_u32.into();
// or
let height = Height::from(0_u32);
// or perhaps even
let height = Height::from(0);
```

**Comment by greg-szabo** [comment]
```
let height = Height::from(0);
```
is problematic because it defaults to i32 which can be negative. :( But an explicit constant like 0_u32 works fine.

**Comment by adizere** [comment]
This is just to document the current state of `Height` data type:

The raw object for `Height` seems to be `i64`:

https://github.com/informalsystems/tendermint-rs/blob/0681df8469a5bf73a17fe84f59ffbd21d65f7858/tendermint/src/block/height.rs#L18

This corresponds to the protobuf raw type from tendermint

https://github.com/informalsystems/tendermint-rs/blob/da9e1773247afccadb855c21afb5601a84f85558/proto/src/prost/tendermint.consensus.rs#L6

However... the domain object Height wraps around a `u64` (not a `i64`), which makes sense. 

https://github.com/informalsystems/tendermint-rs/blob/0681df8469a5bf73a17fe84f59ffbd21d65f7858/tendermint/src/block/height.rs#L16

Digging a bit further, we find another type definition for raw Height, namely [the struct `(u64, u64)`](https://github.com/informalsystems/ibc-rs/blob/e3a8384830850a3837bc9aa31bd8cfe2bd7c34a3/proto/src/prost/ibc.client.rs#L106) used for ibc clients:

```rust
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Height {
    /// the epoch that the client is currently on
    #[prost(uint64, tag="1")]
    pub epoch_number: u64,
    /// the height within the given epoch
    #[prost(uint64, tag="2")]
    pub epoch_height: u64,
}
```

So there seem to be two discrepancies:

1. mismatch between raw and domain object for Height in tendermint (`u64` vs `i64`)
2. mismatch between raw object for Height in IBC and domain object (`struct (u64, u64)` vs `u64`).

**Comment by tony-iqlusion** [comment]
> mismatch between raw and domain object for Height in tendermint (u64 vs i64)

I don't suppose it's possible to fix the actual protos so they use an unsigned value?

**Comment by adizere** [comment]
Fixing the protos should be possible, since `u64` is valid proto type. But my guess is the initial choice of `i64` was motivated from tendermint/tendermint [choice of](https://github.com/tendermint/tendermint/blob/302aec6dcce639763541717063398615f5b1b32e/types/block.go#L318) `int64` for heights. If that's the case, then it's possible we'll be stuck with `i64` in the raw proto. If, however, tendermint/tendermint will adopt a tuple `(u64, u64)` to capture epoch height+number, this should solve it; then we'll just have to adapt tendermint-rs DomainType to match the tuple.

**Comment by tony-iqlusion** [comment]
If there are no situations where a negative value is valid, the protos should use an unsigned type, IMO
