### ISSUE TITLE
Enable MBT for LightClient in Tendermint-go

### ISSUE THREAD

**Issue by andrey-kuprianov** [informalsystems/tendermint-rs#633]
There is already plenty of work done by @melekes in the Tendermint-go repository to integrate our LightClient MBT tests.
See this [issue](https://github.com/tendermint/tendermint/issues/5322) and this [PR](https://github.com/tendermint/tendermint/pull/5461). The current state is that the validation of headers doesn't pass the checks in [block.go](https://github.com/tendermint/tendermint/blob/260cc5dd698941a794cac00652ff06f71a8b9667/types/block.go#L50).

We need to extend the Testgen such that it generates all the necessary fields, and makes the above PR to work. Also things like the [block version](https://github.com/tendermint/tendermint/pull/5461/commits/fac95b0bd50d662c20ac4f705d20ede79ada657f) should be generated automatically.

The workflow for this issue is approximately as follows:
 1. extend Testgen to generate all necessary fields
 2. regenerate the static MBT files
 3. put them locally into the branch of the above PR, and try to execute the test driver
 4. repeat 1-3 until either the tests pass, or some problem in the Go test driver is discovered. In the latter case either try to fix it, or consult with @melekes.

**Comment by andrey-kuprianov** [comment]
@Shivani912 could you please tackle this? I think this is one of our highest priorities at the moment

**Comment by Shivani912** [comment]
Thanks @andrey-kuprianov for summarizing it all here. As we discussed on call, I'm working on it :)

**Comment by Shivani912** [comment]
**Summary of progress so far:**
1. Running the Go MBT tests locally, it initially failed with a similar error:
  ```
  driver_test.go:65: expected ErrNewValSetCantBeTrusted, but got invalid header: untrustedHeader.ValidateBasic failed:        commit signs block 087B7331071C949631B118FF713F146A80131D62930388172B728D0D5CD3AAAF, header is block 314CBA129CBF1C5E51DFEF5446D9FB4000DA953BEFE0937817843A0F9E996F80
  ```
- This failure was because of [these](https://github.com/tendermint/tendermint/pull/5461#issuecomment-709079980) manual changes to json test files. These were made because Go runs at a block version of 11 whereas we were using 0. 
- Regenerated MBT test files with block version at 11 and that solved the problem.


2. Now, we fail with error:
```
expected ErrNewValSetCantBeTrusted, but got wrong signature (#0): 50C1C5CDA2D90B9152C214B5280A79344B33F9D3A2A3B05CF1C06596D45CEB4C64AF9F82412C7FF394A11926555514EE20D2CC9AA4BD6CA4231BD37B79BEB804
```

- Since the test files we run are huge (with many blocks to verify) and to narrow down the issue a little bit, I reduced the test  to a single block verification and ran it on both Rust and Go MBT and got the same result as before.
- Suspected there might be a discrepancy between the way both implementation calculates `VoteSignBytes` and yes there is. Following were the results of the exact same `Vote`'s `sign_bytes`:

  **Rust's sign bytes:**
  ```
  [74, 8, 2, 17, 4, 0, 0, 0, 0, 0, 0, 0, 25, 1, 0, 0, 0, 0, 0, 0, 0, 34, 36, 10, 32, 14, 181, 4, 147, 0, 163, 191, 106, 72, 170, 16, 6, 57, 216, 26, 194, 235, 121, 189, 120, 250, 34, 140, 12, 28, 17, 103, 107, 33, 228, 172, 53, 18, 0, 42, 2, 8, 5, 50, 10, 116, 101, 115, 116, 45, 99, 104, 97, 105, 110]
  ```
  **Go's sign bytes:**
  ```
  [108 8 2 17 4 0 0 0 0 0 0 0 25 1 0 0 0 0 0 0 0 34 70 10 32 39 60 79 40 67 52 117 65 197 173 56 128 56 125 233 67 57 8 78 187 63 113 141 121 14 219 41 115 104 182 251 227 18 34 18 32 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 42 2 8 5 50 10 116 101 115 116 45 99 104 97 105 110]
  ```

- Chatted briefly with @greg-szabo about this. His impression was that this could possibly be because somewhere we might be using an invalid `Timestamp` and there is a possible discrepancy between how Go and Rust handles an invalid one.

**Next steps:** Further narrow down the problem to be able to pinpoint the issue by going into a debugging session focused around `sign_bytes` calculation code.

**Comment by melekes** [comment]
@Shivani912 thank you for the update! https://github.com/tendermint/spec/issues/175 - the way header's (block ID) hash is calculated is different right now in Go / Rust implementations. I will try to fix it today.

**Comment by Shivani912** [comment]
> @Shivani912 thank you for the update! [tendermint/spec#175](https://github.com/tendermint/spec/issues/175) - the way header's (block ID) hash is calculated is different right now in Go / Rust implementations. I will try to fix it today.

Hmm, i don't understand. If the calculation is different then how are the current tests passing this particular check?

**Comment by melekes** [comment]
Oops, somehow missed `simple_hash_from_byte_vectors` in Rust version, which builds a Merkle tree. Please ignore.

**Comment by Shivani912** [comment]
Hey @melekes, with PR #647 I've tried to fix the issues from MBT side and re-generated the test files which you can directly run for Go code. I did the same on my computer and it fails with this error:

```
expected ErrInvalidHeader, but got expected old header next validators (5A69ACB73672274A2C020C7FAE539B2086D30F3B7E5B168A8031A21931FCA07D) to match those from new header (C8CFFADA9808F685C4111693E1ADFDDBBEE9B9493493BEF805419F143C5B0D0A)
```

This is failing for file `MC4_4_faulty_Test3NotEnoughTrustFailure.json` which does expect to fail with "invalid next_validators_hash" in the `Header` and so it is expected to result with an `Invalidheader` error. I'd suggest to wrap the above mentioned error message with `ErrInvalidHeader` in Go code.

Hope this makes sense! :))

**Comment by andrey-kuprianov** [comment]
@Shivani912 , thanks for fixing the issues! The relationship wrt. verdicts is as follows:

In the model, as well as in the Rust code, we distinguish between the three broad categories of outcomes:
 - **Success**: passed verification
 - **Invalid**: datastructure checks were not successful. Everything unexpected falls here, like hash mismatch, non-monotonic time, etc.
 - **NotEnoughTrust**: the datastructures seem OK, but there is not enough trust to validate the header given the known information; i.e. more intermediate headers should be fetched.

The current problem is that the Go test driver needs to be modified a bit, to include validator hash mismatch under the "Invalid" category. No modifications to the Go's LightClient itself need to be made, only to broaden the categorization of errors in the test driver.

Hope that helps, @melekes. Please let us know if further assistance is needed from our side.

**Comment by Shivani912** [comment]
Thanks @andrey-kuprianov for explaining that! Also, I think it'll be helpful to add description of categories in a README for future. Please correct me if it already exists

**Comment by melekes** [comment]
amazing work everyone ❤️

**Comment by andrey-kuprianov** [comment]
@melekes could you please try the static tests from this branch? https://github.com/informalsystems/tendermint-rs/tree/andrey/replace-single-step

I have merged the latest changes from Shivani into this branch, so I hope the tests should be parsed in Go without problems. But there are now many more tests, and I am curious how the Go implementation will behave against those...
