### ISSUE TITLE
Bug in JSON encoding of PartSetHeader

### ISSUE THREAD

**Issue by Shivani912** [informalsystems/tendermint-rs#645]
**Context**
Found this very interesting situation while working on #633. For background, signature verification fails on Go implementation for Model Based Tests. Digging deeper into this, found that both (Go and Rust) produces different `sign_bytes` for the same vote (fed through JSON file). Decoding these bytes revealed two things:
1. Rust implementation had a completely empty `PartSetHeader`, while
2. Go implementation was missing `PartSetHeader.Total`, but had `PartSetHeader.Hash` (@melekes)

**Problem**
Empty `PartSetHeader.Hash` is JSON-encoded as a string of all 0's. This is incorrect because we never expect to receive such data. An empty one in Go is represented as an empty vector. 
(Thanks @greg-szabo for finding this!)

**Options for Next Steps**
1. Fix this issue, but can take about a week - downside is that MBT will keep failing for Tendermint-go until this is done, might block progress there
2. Make a temporary fix to unblock MBT while we work on a permanent fix

**Comment by melekes** [comment]
nice find @Shivani912 & @greg-szabo 👍 let me know if you need my help with anything (both on Go and Rust side)

**Comment by greg-szabo** [comment]
I wonder, if  #664 have fixed this for you. (Empty hash is encoded/decoded as no block_id.) Can you double-check?

**Comment by andrey-kuprianov** [comment]
@Shivani912 could you please check this?

**Comment by Shivani912** [comment]
Yes, this is fixed :) Thank you @greg-szabo !
