### ISSUE TITLE
Make non-nullable items not optional in domain structs

### ISSUE THREAD

**Issue by greg-szabo** [informalsystems/tendermint-rs#649]
The protobuf definitions have some Go-related annotations that Prost doesn't understand. The one that says `gogoproto.nullable=false` mean that those structs should never be null. Prost still defines them as optional, but in our domain types we can assume they will also be filled (and send errors during conversion if they are not). Since knowing this requires to check in the protobuf definition file, in some cases, we implemented domain types fields as optional when it's not necessary.

To make life easier (and more to the point) we should filter all types in the protobug messages and fix the domain types where protobuf defined nullable=false.

**Comment by melekes** [comment]
We'll probably ditch `gogoproto` https://github.com/tendermint/tendermint/issues/5446 in next major release. So you might want to just wait it out.

**Comment by greg-szabo** [comment]
We'll wait it out, thanks for the context, Anton!
