### ISSUE TITLE
Support consensus state in tendermint rpc

### ISSUE THREAD

**Issue by zmanian** [informalsystems/tendermint-rs#674]
I would like to be able to write consensus monitoring systems in rust.

The consensus_state endpoint can be very helpful for doing that.

This can be used to badger validators who aren't live yet.

**Comment by thanethomson** [comment]
@zmanian, do you want the RPC to automatically parse the [vote strings](https://github.com/tendermint/tendermint/blob/e820e68acd69737cfb63bc9ccca5f5450a42b5cf/types/vote.go#L119) and [vote bit arrays](https://github.com/tendermint/tendermint/blob/e820e68acd69737cfb63bc9ccca5f5450a42b5cf/types/vote_set.go#L518) returned by this endpoint?

**Comment by zmanian** [comment]
So I started to make something like this.

https://github.com/iqlusioninc/tm-launch-monitor/blob/main/main.go#L94-L122

This kind of tooling is sorely needed in the tendermint ecosystem.

Pulling apart the vote strings is a bit messy and I think it's why no standard blame tool has emerged.

I can see more usage for parsed vote strings than I can for the vote bit array.

**Comment by thanethomson** [comment]
Awesome, I've just added rudimentary support for the `consensus_state` endpoint in #719, but it just returns the vote strings and vote bit arrays in their string form. I'll work on parsing them tomorrow.

**Comment by thanethomson** [comment]
@zmanian, do you think the abstractions [here](https://github.com/informalsystems/tendermint-rs/pull/719/files#diff-ab5fd456d6899ca28eb6bbb2b0fa25f0ee6a52b07e5824915bc929c22302dced) would work for you for the vote strings?
