### ISSUE TITLE
Automation for stale issues

### ISSUE THREAD

**Issue by thanethomson** [informalsystems/tendermint-rs#688]
During our planning session today we were discussing the possibility of implementing some kind of automation for dealing with stale issues. What are our options on this front?

**Comment by thanethomson** [comment]
Would the following simple heuristic work for us?

* If the issue has an assignee or is attached to a milestone, don't touch it.
* Otherwise:
  * If the issue's been open for 30 days without any activity, mark it as stale (as a way of pinging the original participants to either assign the issue to someone or to a milestone)
  * If the issue's been open for 60 days and still nobody's responded, close it.

It should be easy enough to implement with something like this [stale action](https://github.com/actions/stale).

---

A previous argument against using some kind of automated process to deal with stale issues is that this isn't a large, high-traffic project and we shouldn't need this sort of automation, because we should be able to stay on top of things.

The trouble with this perspective is that it's cheap to create an issue, but far more expensive to triage it, especially when you don't have the full context on it or if the issue's vague. Also, sometimes issues buried deep in the issues list, by happy coincidence, inadvertently become non-issues - should we really have to dedicate triaging effort to digging up context and verifying that those kinds of issues have been addressed?

I suppose the question comes down to: **where do we want to spend our (limited) attention**? I'd personally like to spend zero attention on non-issues and let them fade quietly into the night 😁

**Comment by xla** [comment]
While the argument with regards to low effort to create issues might be true for cases where people look for support for proper setup and such, it's not strong enough of an argument to apply to all kind of issues.

There is a large range of issues which hold important information which stay relevant over long time periods, just current capacity and priority prevents them from being resolved more swiftly. To illustrate the point, in the tendermint go project just now 2 1/2 year old issues were closed because the dialog around led to informed next steps in form of an ADR and likely follow-up implementations.

**Comment by marbar3778** [comment]
[Go-Tendermint](https://github.com/tendermint/tendermint/blob/4f91eaefb8008c0877054f2c3af50f35deeb9e30/.github/workflows/stale.yml#L1-L1) implements this for PRs using [stale bot](https://github.com/actions/stale) but it's a three-line addition to do issues as well

**Comment by thanethomson** [comment]
> There is a large range of issues which hold important information which stay relevant over long time periods, just current capacity and priority prevents them from being resolved more swiftly.

True. And my desire's not at all to cull those kinds of issues automatically. In an urgent/important framework, I'm hoping to automate away the non-urgent, non-important issues in a simple, shared, decentralized way.

In one of our upcoming team meetings we should chat more about our general issue housekeeping 😁

**Comment by thanethomson** [comment]
We've decided for now in favour of #721 instead of automation. Perhaps in future we might add such automation to the project, but #721 will go a long way to avoiding this problem in the first place.
