### ISSUE TITLE
GitHub issue template(s) to include "definition of done"

### ISSUE THREAD

**Issue by thanethomson** [informalsystems/tendermint-rs#721]
As per our most recent call, it'd be great if we could get better at clearly defining the desired outcome for an issue. Ultimately, for each issue, we want to definitively know: *can this issue be closed right now?* And if it's difficult to tell, it means that the issue's not defined well enough.

**Comment by xla** [comment]
We started to use *Acceptance Criteria* in the seed issues, inspired by long chats with @brapse
