### ISSUE TITLE
p2p: test SecretConnection handshake

### ISSUE THREAD

**Issue by melekes** [informalsystems/tendermint-rs#734]
Write a test for Secret connection, which covers the whole handshake (exchanging ephemeral keys and so on) #happypath. We probably also want to cover additional scenarios like when a peer is not responding or responding with invalid data (do we want to try fuzzing here?) at each step of the handshake.

### Acceptance Criteria

* [x] happy path test
* [x] test where the remote peer is not responding
* [x] test where the remote peer provides invalid data

**Comment by melekes** [comment]
```rs
    #[test]
    fn test_evil_peer_does_not_share_eph_key() {
        let (_pipe1, pipe2) = pipe::bipipe_buffered();

        let thread1 = thread::spawn(|| {
            let mut csprng = OsRng {};
            let privkey1: ed25519::Keypair = ed25519::Keypair::generate(&mut csprng);
            let conn1 = SecretConnection::new(pipe2, &privkey1, Version::V0_34);
            assert_eq!(conn1.is_ok(), true);
        });

        thread1.join().expect("thread1 has panicked");
    }
```

test where peer is not responding fails at the moment because we're using blocking reads (`read_exact`). we probably need to use `mio` or threads (which will require static lifetime) to read with a timeout.

**Comment by xla** [comment]
> test where peer is not responding fails at the moment because we're using blocking reads (`read_exact`). we probably need to use `mio` or threads (which will require static lifetime) to read with a timeout.

This could be done in a follow-up after the tests are finalised, as first improvement based on it.
