### ISSUE TITLE
p2p: rewrite SecretConnection handshake using the state machine pattern

### ISSUE THREAD

**Issue by melekes** [informalsystems/tendermint-rs#735]
Rewrite the SecretConnection handshake using the learnings from https://github.com/informalsystems/tendermint-rs/pull/708. The state machine pattern hopefully will allow us: a) to test each step (~state) separately b) enforce the rules (i.e. one can't go to creating challenge (state 2) before receiving the remote ephemeral key (state 1).

Resources:

- https://hoverbear.org/blog/rust-state-machine-pattern/
- https://deislabs.io/posts/a-fistful-of-states/

**Comment by xla** [comment]
Another one on the topic: [Type-level Programming in Rust](https://willcrichton.net/notes/type-level-programming/)
