### ISSUE TITLE
Non-deterministic hanging test in tendermint_p2p::secret_connection

### ISSUE THREAD

**Issue by thanethomson** [informalsystems/tendermint-rs#841]
I was running some tests today (on `master`) and found one of the P2P tests hanging indefinitely: https://github.com/informalsystems/tendermint-rs/blob/4b0318c4c7e2150565c5ded593280df4b9ac7ad9/p2p/src/secret_connection.rs#L539

Not sure if this is caused by a problem in the `pipe` crate or by the non-deterministic nature of who reads/writes first from/to the bidirectional buffer when spawning the write and read threads in the test.

cc @melekes @xla 

**Steps to reproduce**

It's not guaranteed to reproduce the issue, but if I run the following around 5-10 times the test usually hangs at least once:

```
cargo test -p tendermint-p2p --all-features
```

**What's the definition of "done" for this issue?**

When we can reliably execute the test without it hanging.

**Comment by melekes** [comment]
Sorry about this. I thought I could use `pipe` crate (a a synchronous memory pipe with buffered writer; https://docs.rs/pipe/0.4.0/pipe/) with our tests, but maybe it's not possible. Our implementation (specifically share_* functions https://github.com/informalsystems/tendermint-rs/blob/e4eb6b927dd88f89d7bc9016f7e6517bae9b96b9/p2p/src/secret_connection.rs#L418) rely on async transport.
