### ISSUE TITLE
kvstore-integration test hanging in CI

### ISSUE THREAD

**Issue by thanethomson** [informalsystems/tendermint-rs#843]
The vast majority of CI runs this past while have resulted in the `kvstore-integration-latest` test hanging, and it's unclear as to why unless you watch the run take place.

It looks like there's some kind of serialization incompatibility with the latest versions of Tendermint, and this causes one of the subscription tests to hang indefinitely. A reasonable solution here would be to impose a time limit on the subscription test's execution.

Here's some of the test output:

```
...
running 13 tests
test rpc::abci_query ... FAILED
test rpc::abci_info ... FAILED
test rpc::block ... FAILED
test rpc::block_results ... FAILED
test rpc::commit ... FAILED
test rpc::blockchain ... FAILED
test rpc::consensus_state ... ok
test rpc::genesis ... ok
test rpc::health ... ok
test rpc::net_info ... ok
test rpc::status_integration ... FAILED
test rpc::transaction_subscription ... FAILED
test rpc::subscription_interface ... test rpc::subscription_interface has been running for over 60 seconds
```

**Steps to reproduce**

Submit a PR and then watch the `kvstore-integration` test's execution.

**What's the definition of "done" for this issue?**

When this test either passes or fails within a reasonable period of time (1-5mins). We can look at fixing the serialization compatibilities in a future PR targeting `tendermint/tendermint:latest`.

**Comment by vitorenesduarte** [comment]
I was suffering with this in #840. A quick fix in the meantime might be to add a timeout to the whole CI job: https://github.com/informalsystems/tendermint-rs/pull/840/commits/a43add3c9fa3ed099fa47e4792607da17f2ce7d1

**Comment by thanethomson** [comment]
The problem's probably coming from the fact that the Tendermint node itself is hanging at the moment (at least on the current `tendermint/tendermint:latest` Docker image), which is something the Tendermint team's going to address soon.

As such, since such changes can interfere with our CI pipeline, I'd say the best course of action is just to not run the test on every PR (it was a nice-to-have anyways, since we don't fail the CI if the test fails) and rather run it as a "cron job" of sorts.
