### ISSUE TITLE
prost 0.7 uses core types instead of std

### ISSUE THREAD

**Issue by greg-szabo** [informalsystems/tendermint-rs#871]
Prost 0.7 moved all internally used types (Vec, String, etc) generated from the core library, instead of std.

This is cool for our no-std approach but will it have any impact on downstream projects?

**What's the definition of "done" for this issue?**
Get an answer if we're ok going ahead with using `core` types in `tendermint-proto`.
We should rebuild the proto library if this is ok.

**Comment by tony-iqlusion** [comment]
`std` is just a facade for `core`/`alloc` anyway. It's not really an issue.

**Comment by thanethomson** [comment]
#862 rebuilds the `tendermint-proto` crate referencing `core` instead: https://github.com/informalsystems/tendermint-rs/pull/862/files#diff-5490ef56810f271524d11c1ae79f36be9ec2db0daca7d9f2227dc430efb917b7
