### ISSUE TITLE
Pre-v0.20.0 release tracking ticket for: `k256` v0.9 update, #873, upstreaming cosmos-sdk-rs's `AccountId`

### ISSUE THREAD

**Issue by tony-iqlusion** [informalsystems/tendermint-rs#892]
This is a tracking issue for some changes I'd like to get into tendermint-rs v0.20, some of which I've discussed with @thanethomson:

- [x] #894: `k256` v0.9
- [ ] #873: refactor public keys (PR: #900)
- [ ] #895: upstream `AccountId` from cosmos-sdk-rs

## #894: `k256` v0.9

I plan on releasing a new version of `k256` (secp256k1 library) in the next few days. Hopefully I can get an upgrade in before the next release.

The biggest reason why you'd want this is it eliminates `bitvec` as a mandatory dependency, and `bitvec` has a number of transitive dependencies, so it would help cutting down on the overall dependency count.

For us at iqlusion, we're writing a key manager for Gravity Bridge (based on Signatory) which uses tendermint-rs and would like to be able to take advantage of the latest features in this crate.

## #873: refactor public keys (PR: #900)

Right now the `tendermint::public_key::Secp256k1` type performs no validation of public keys. As documented in #873, ensuring keys are valid is a beneficial invariant to maintain.

As it were,  `tendermint::public_key::Ed25519` used to behave this way. When it was switched to validate public keys, some issues with the test vectors in use were discovered. I think it would be good to ensure keys are validated (i.e. checked to decode to curve points which are valid solutions to the curve equation) to prevent similar bugs.

## #895: upstream `AccountId` from cosmos-sdk-rs

This one seems somewhat debatable, but as part of working on cosmos-sdk-rs I wrote a type for representing Bech32 `AccountId`s:

https://github.com/cosmos/cosmos-rust/blob/5999ee12f658195ebc57e84adaff4bff9c425553/cosmos-sdk-rs/src/base.rs

This is effectively a newtype whose contents are always valid Bech32 and as such also carries along the "human readable prefix" . The current `tendermint::account::Id` (which I think I'm largely guilty for) does not.

**Comment by thanethomson** [comment]
With regard to the `AccountId` type, what value does this add at the `tendermint-rs` level? It's not something that Tendermint itself really understands, is it?

**Comment by tony-iqlusion** [comment]
FYI, PRs are now open for all of these. #894 was the only one I really cared strongly about and it's landed.

**Comment by tony-iqlusion** [comment]
Will go ahead and close this issue as the relevant PRs are all open

**Comment by thanethomson** [comment]
Thanks @tony-iqlusion! Yeah to me it makes sense to rather keep `AccountId` as part of cosmos-sdk-rs :+1:

Will look at doing a pruning of some of the domain types soon to ensure they're relevant at the Tendermint level.
