### ISSUE TITLE
Newbie Learning Materials about tendermint

### ISSUE THREAD

**Issue by DaviRain-Su** [informalsystems/tendermint-rs#937]
Hi, is there any information for newbies to learn`tendermint` and how to contribute to `tendermint-rs`.

**Comment by thanethomson** [comment]
https://docs.tendermint.com/ is a good place to start learning about Tendermint, and our [contributing guidelines](https://github.com/informalsystems/tendermint-rs/blob/master/CONTRIBUTING.md) should help for people wanting to contribute.

Are those the kinds of resources you're looking for?

**Comment by thanethomson** [comment]
@DaviRain-Su, is that documentation sufficient for you? Is there some other kind of contribution info you're looking for?
