### ISSUE TITLE
Support Secp256k1 signature verification for PublicKey

### ISSUE THREAD

**Issue by lyqingye** [informalsystems/tendermint-rs#939]
I hope Publickey can support the verification of secp256 publickey signature
https://github.com/informalsystems/tendermint-rs/blob/master/tendermint/src/public_key.rs#L151

I think the issue: https://github.com/informalsystems/ibc-rs/issues/1155  is related to this
When some chains use secp256k1 as the consensus PublicKey type, the tendermint-light-client will not be able to verify the signature of the light block, such as bandchain.

**Comment by RiccardoM** [comment]
Hey @thanethomson, is it possible to have an update on this? It is currently blocking informalsystems/ibc-rs#1155 which actually makes it impossible to communicate with some chains like Band Protocol

**Comment by romac** [comment]
@RiccardoM I have a WIP branch which adds support for ECDSA Secp256k1 signatures. Will try to include in the next Hermes release.

**Comment by tony-iqlusion** [comment]
Happy to help review PRs for this
