### ISSUE TITLE
Upstream integration testing functionality from cosmos-sdk-rs?

### ISSUE THREAD

**Issue by tony-iqlusion** [informalsystems/tendermint-rs#944]
#942 (which I'm basically responsible for) seems like the sort of problem which would've been caught easily by a live integration test against a Tendermint RPC endpoint.

I wrote a handful of simple utility functions to assist integration testing against a single-node gaiad as part of cosmos-sdk-rs:

https://github.com/cosmos/cosmos-rust/blob/7ff213318ddc93440bbe6030e8258631b2bd8b59/cosmos-sdk-rs/src/dev.rs

Would there be any interest in upstreaming these to tendermint-rs? It seems useful for e.g. integration testing `tendermint-rpc` in a way which could run as part of CI.

**Comment by thanethomson** [comment]
We currently have integration testing against the kvstore in the [tools folder](https://github.com/informalsystems/tendermint-rs/blob/e824bfccb10a3a7d4eaad877fe2fd2fd782a2984/tools/kvstore-test/tests/tendermint.rs), as well as our [rpc-probe](https://github.com/informalsystems/tendermint-rs/tree/master/tools/rpc-probe) which we usually use to generate fixtures for the RPC tests (see [here](https://github.com/informalsystems/tendermint-rs/blob/e824bfccb10a3a7d4eaad877fe2fd2fd782a2984/rpc/tests/kvstore_fixtures.rs)).

We just need to generate those fixtures for the `/tx` endpoint and add an integration test against the kvstore and we'll automatically detect regressions [here in CI](https://github.com/informalsystems/tendermint-rs/blob/e824bfccb10a3a7d4eaad877fe2fd2fd782a2984/.github/workflows/test.yml#L108).

**Comment by tony-iqlusion** [comment]
Aha, sounds good then
