### ISSUE TITLE
Make `tendermint_rpc:method` a public module

### ISSUE THREAD

**Issue by batconjurer** [informalsystems/tendermint-rs#950]
In order for users to implement the tendermint_rpc::request::Request trait (which is public), the return type of the `method` function is `Method` (which is currently private). There are probably ways around this, e.g. converting to a `Method` from a string but that adds overhead and changes a compile time check to a run-time check. Given that I see nothing worth hiding in the `method` module, I think making it public would be a great idea.

**Comment by thanethomson** [comment]
As far as I can see, the `Method` enum is public: https://github.com/informalsystems/tendermint-rs/blob/bbad6faf622fe3b812075969e436e5a52353be2f/rpc/src/lib.rs#L58

Are you having trouble accessing it?

**Comment by batconjurer** [comment]
Not now. Strange. Ok, no problems!
