### ISSUE TITLE
`url` crate used by `tendermint` does not support no_std

### ISSUE THREAD

**Issue by soareschen** [informalsystems/tendermint-rs#985]
The struct `url::Url` is used inside `tendermint::net`, however the `url` crate cannot work under no_std. We would have to either move `tendermint::net` to a separate crate, or find an alternative crate that supports no_std.

Note that the `tendermint::net` module is not used in any part of the `ibc` crate. However it is not clear whether it is used indirectly by `ibc` elsewhere, which would complicate the issue.

There is a recent pending PR in August 2021 to support no_std in `url`: servo/rust-url#717. However it is not clear when it will get merged. An alternative solution would be to contribute upstream and push for that PR to get merged and released soon.

**Comment by seanchen1991** [comment]
Does #986 address the `url` crate's `no_std` compliance in any way?

**Comment by soareschen** [comment]
> Does #986 address the `url` crate's `no_std` compliance in any way?

`tendermint-config` do not have to be `no_std`-compliant. Only `tendermint` crate needs to be, and in this PR we have removed the `url` dependency in `tendermint` crate itself.

**Comment by soareschen** [comment]
This has been addressed with the use of `Url` moved to `tendermint-config`.
