### ISSUE TITLE
Track compatibility of "amino types" to go tendermint 

### ISSUE THREAD

**Issue by Liamsi** [informalsystems/tendermint-rs#99]
Original issue here: https://github.com/tendermint/kms/issues/48

**Comment by ebuchman** [comment]
Looks like this is really just a tracking issue for when Tendermint Core goes full proto? Should we close it for now and open a new one soon that better tracks that transition to proto story more holistically?

**Comment by Liamsi** [comment]
Makes sense. Closing.
